### PR TITLE
Aishell Zipformer

### PR DESCRIPTION
**Pull request by marcoyang1998**
This PR adds Zipformer (pruned_transducer_stateless7) to Aishell.

It achieves the following WERs with `modified_beam_search`:

| Model | epoch-avg | dev | test |
| -------| -------------| ----| -----|
| Zipformer | 42-6 | 4.4 | 4.81 |
| `pruned_transducer_stateless2` | 72-14 | 4.63 | 5.07 |

Will upload the corresponding models to huggingface.

### CODE REVIEW

**Comment by csukuangfj** [comment]
Could you update README.md and RESULTS.md?

**Comment by marcoyang1998** [comment]
> Could you update README.md and RESULTS.md?

Just did it.

**Review by yfyeung — APPROVED** [review]

**Comment by marcoyang1998** [comment]
I tested with `--context-size=2`, the model performs much worse than `--context-size=1`.

**Comment by danpovey** [comment]
> I tested with `--context-size=2`, the model performs much worse than `--context-size=1`.

Ah-- how much worse?  And what context size did the baseline use-- is it possible that the apparent improvement just came from reducing the context size?

**Comment by marcoyang1998** [comment]
> Ah-- how much worse? And what context size did the baseline use-- is it possible that the apparent improvement just came from reducing the context size?

Here is the comparison:
| Context Size | dev | test |
| -------|  ----| -----|
| 1 | 4.61 | 5.02 |
| 2 | 5.51 | 5.9 |
The models in previous recipes are also trained with `--context-size=1`, so the comparison is fair.

**Comment by TeaPoly** [comment]
> This PR adds Zipformer (pruned_transducer_stateless7) to Aishell.
> 
> It achieves the following WERs with `modified_beam_search`:
> 
> Model	epoch-avg	dev	test
> Zipformer	42-6	4.4	4.81
> `pruned_transducer_stateless2`	72-14	4.63	5.07
> Will upload the corresponding models to huggingface.

So this result is training with `--context-size=1`.

**Comment by marcoyang1998** [comment]
> So this result is training with` --context-size=1`.

Yes.

**Review by csukuangfj — COMMENTED** [review]
Thanks! Left some minor comments.

**Pull request merged**
