### PR TITLE
updated grad check for `optim.py`

### PR DESCRIPTION
**Pull request by JinZr**

### CODE REVIEW

**Comment by danpovey** [comment]
I think this is OK to merge as long as you can run
python3 ./optim.py
and the test seems to run without crashing

**Comment by JinZr** [comment]
the test finished without crushing, i'll see if fangjun is available to do
the reviewing, thanks!

**Review by danpovey — COMMENTED** [review]
its OK

**Comment by danpovey** [comment]
its OK, reviewed & merged myself

**Pull request merged**
