### PR TITLE
Support exporting to ONNX format

### PR DESCRIPTION
**Pull request by csukuangfj**
## TODOs

- [x] ~Merge `encoder.onnx`, `decoder.onnx`, and `joiner.onnx` into a single `.onxx` file.~
- [ ] ~Also need to export `joiner.encoder_proj` and `joiner.decoder_proj` and merge them into a single `.onnx` file~
- [ ] Integrate changes from https://github.com/EmreOzkose/icefall/tree/onnx
       (Use `onnx_beam_search.py` and `onnx_pretrained.py`)
- [x] `export.py` needs to be refactored
- [x] Add more tests to `onnx_check.py`

@EmreOzkose Could you have a look at this PR?   I rewrite `as_strided` with `torch.gather`.
I plan to integrate your changes about `onnx_beam_search.py` and `onnx_pretrained.py`.

From https://github.com/k2-fsa/sherpa/issues/51#issuecomment-1196781073

I suggest that we merge all exported `.onnx` files into a single file 
to make deployment easier. (Maybe you can help with it.)

### CODE REVIEW

**Comment by yuekaizhang** [comment]
Would you mind keeping two options? One for merged onnx single model file, another for three separate part: encoder, decoder, joiner. Latter would be helpful to deploy in triton.

**Comment by csukuangfj** [comment]
> Would you mind keeping two options? One for merged onnx single model file, another for three separate part: encoder, decoder, joiner. Latter would be helpful to deploy in triton.

Sure.

**Comment by csukuangfj** [comment]
Note: I just reverted the changes about combining exported encoder/decoder/joiner into a single ONNX model.
It takes a lot of time for ONNX to extract a sub-graph from the combined model, e.g., more than 1 hour to extract the encoder model from the combined model. I think the reason is that there are a lot of nodes in the graph and onnx needs to check which node is reachable for a given input.

The following shows some logs of `onnx_check.py`. I killed it after it gets stuck for more than one hour.
```
2022-07-30 10:29:08,862 INFO [onnx_check.py:204] Loading ./pruned_transducer_stateless3/exp-0.9/all_in_one.onnx
2022-07-30 10:29:10,128 INFO [onnx_check.py:208] Extracting encoder
^CTraceback (most recent call last):
  File "./pruned_transducer_stateless3/onnx_check.py", line 227, in <module>
    main()
  File "/ceph-fj/fangjun/software/py38/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "./pruned_transducer_stateless3/onnx_check.py", line 209, in main
    encoder_onnx = extractor.extract_model(
  File "/ceph-fj/fangjun/software/py38/lib/python3.8/site-packages/onnx/utils.py", line 151, in extract_model
    nodes = self._collect_reachable_nodes(input_names, output_names)
  File "/ceph-fj/fangjun/software/py38/lib/python3.8/site-packages/onnx/utils.py", line 72, in _collect_reachable_nodes
    self._dfs_search_reachable_nodes(name, input_names, reachable_nodes)
  File "/ceph-fj/fangjun/software/py38/lib/python3.8/site-packages/onnx/utils.py", line 63, in _dfs_search_reachable_nodes
    self._dfs_search_reachable_nodes(name, graph_input_names, reachable_nodes)
  File "/ceph-fj/fangjun/software/py38/lib/python3.8/site-packages/onnx/utils.py", line 63, in _dfs_search_reachable_nodes
    self._dfs_search_reachable_nodes(name, graph_input_names, reachable_nodes)
  File "/ceph-fj/fangjun/software/py38/lib/python3.8/site-packages/onnx/utils.py", line 63, in _dfs_search_reachable_nodes
    self._dfs_search_reachable_nodes(name, graph_input_names, reachable_nodes)
  [Previous line repeated 39 more times]
  File "/ceph-fj/fangjun/software/py38/lib/python3.8/site-packages/onnx/utils.py", line 57, in _dfs_search_reachable_nodes
    if node in reachable_nodes:
KeyboardInterrupt
```

**Comment by EmreOzkose** [comment]
> Note: I just reverted the changes about combining exported encoder/decoder/joiner into a single ONNX model. It takes a lot of time for ONNX to extract a sub-graph from the combined model, e.g., more than 1 hour to extract the encoder model from the combined model. I think the reason is that there are a lot of nodes in the graph and onnx needs to check which node is reachable for a given input.
> 
> The following shows some logs of `onnx_check.py`. I killed it after it gets stuck for more than one hour.
> 
> ```
> 2022-07-30 10:29:08,862 INFO [onnx_check.py:204] Loading ./pruned_transducer_stateless3/exp-0.9/all_in_one.onnx
> 2022-07-30 10:29:10,128 INFO [onnx_check.py:208] Extracting encoder
> ^CTraceback (most recent call last):
>   File "./pruned_transducer_stateless3/onnx_check.py", line 227, in <module>
>     main()
>   File "/ceph-fj/fangjun/software/py38/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
>     return func(*args, **kwargs)
>   File "./pruned_transducer_stateless3/onnx_check.py", line 209, in main
>     encoder_onnx = extractor.extract_model(
>   File "/ceph-fj/fangjun/software/py38/lib/python3.8/site-packages/onnx/utils.py", line 151, in extract_model
>     nodes = self._collect_reachable_nodes(input_names, output_names)
>   File "/ceph-fj/fangjun/software/py38/lib/python3.8/site-packages/onnx/utils.py", line 72, in _collect_reachable_nodes
>     self._dfs_search_reachable_nodes(name, input_names, reachable_nodes)
>   File "/ceph-fj/fangjun/software/py38/lib/python3.8/site-packages/onnx/utils.py", line 63, in _dfs_search_reachable_nodes
>     self._dfs_search_reachable_nodes(name, graph_input_names, reachable_nodes)
>   File "/ceph-fj/fangjun/software/py38/lib/python3.8/site-packages/onnx/utils.py", line 63, in _dfs_search_reachable_nodes
>     self._dfs_search_reachable_nodes(name, graph_input_names, reachable_nodes)
>   File "/ceph-fj/fangjun/software/py38/lib/python3.8/site-packages/onnx/utils.py", line 63, in _dfs_search_reachable_nodes
>     self._dfs_search_reachable_nodes(name, graph_input_names, reachable_nodes)
>   [Previous line repeated 39 more times]
>   File "/ceph-fj/fangjun/software/py38/lib/python3.8/site-packages/onnx/utils.py", line 57, in _dfs_search_reachable_nodes
>     if node in reachable_nodes:
> KeyboardInterrupt
> ```

I think it is a common problem, there is a way to extract models [here](https://github.com/PINTO0309/sne4onnx/blob/0662133b009950f2501a307fd252a48c97785d82/sne4onnx/onnx_network_extraction.py#L35). I tried it and it works (onnx_check.py works without an assertion)

```
def extract_model(input_onnx_file_path, input_op_names, output_op_names, non_verbose=False):
    import onnx_graphsurgeon as gs

    onnx_graph = onnx.load(input_onnx_file_path)
    onnx_graph = onnx.shape_inference.infer_shapes(onnx_graph)
    graph = gs.import_onnx(onnx_graph)
    graph.cleanup().toposort()

    # Extraction of input OP and output OP
    graph_node_inputs = [graph_nodes for graph_nodes in graph.nodes for graph_nodes_input in graph_nodes.inputs if graph_nodes_input.name in input_op_names]
    graph_node_outputs = [graph_nodes for graph_nodes in graph.nodes for graph_nodes_output in graph_nodes.outputs if graph_nodes_output.name in output_op_names]

    # Init graph INPUT/OUTPUT
    graph.inputs.clear()
    graph.outputs.clear()

    # Update graph INPUT/OUTPUT
    graph.inputs = [graph_node_input for graph_node in graph_node_inputs for graph_node_input in graph_node.inputs if graph_node_input.shape]
    graph.outputs = [graph_node_output for graph_node in graph_node_outputs for graph_node_output in graph_node.outputs]

    # Cleanup
    graph.cleanup().toposort()

    # Shape Estimation
    extracted_graph = None
    try:
        extracted_graph = onnx.shape_inference.infer_shapes(gs.export_onnx(graph))
    except Exception as e:
        extracted_graph = gs.export_onnx(graph)
        if not non_verbose:
            print(
                f'{Color.YELLOW}WARNING:{Color.RESET} '+
                'The input shape of the next OP does not match the output shape. '+
                'Be sure to open the .onnx file to verify the certainty of the geometry.'
            )
    return extracted_graph

def extract_encoder(filename):
    import onnxruntime
    encoder_ = extract_model(filename, ["encoder/x", "encoder/x_lens"], ["encoder/encoder_out", "encoder/encoder_out_lens"], False)
    onnx.save(encoder_, "encoder_.onnx")
    onnx.checker.check_model(encoder_)

    sess = onnxruntime.InferenceSession("encoder_.onnx")
    return sess

encoder_session = extract_encoder(args.onnx_all_in_one_filename)
test_encoder(model, encoder_session_nicely)
```

**Comment by csukuangfj** [comment]
@EmreOzkose 
Thanks for the code.

Could you post how long it will take to extract the encoder model from the combined model?

**Comment by EmreOzkose** [comment]
```
tictoc.tic()
encoder_session = extract_encoder(args.onnx_all_in_one_filename)
tictoc.toc("extract_encoder")
# extract_encoder 4.387611 seconds.
```

**Comment by csukuangfj** [comment]
> ```
> tictoc.tic()
> encoder_session = extract_encoder(args.onnx_all_in_one_filename)
> tictoc.toc("extract_encoder")
> # extract_encoder 4.387611 seconds.
> ```

Wow. That looks great. The original one, which I have removed, takes more than 30 minutes.

Would you mind making a PR after merging this PR? I am making small fixes right now.

**Comment by csukuangfj** [comment]
This PR is ready for review now.

In summary, it includes the following items:

- code to convert `ScaledLinear`, `ScaledConv2d`, and `ScaledConv1d` to their non-scaled counterparts
- export a pretrained model to onnx format
- export a pretrained model with torchscript, supporting both `torch.jit.script()` and `torc.jit.trace()`
- there are tests to cover the exported models

**Review by danpovey — COMMENTED** [review]
Great functionality!
So what are the differences between jit and onnx?  I assume jit it PyTorch-only, but are there differences in how they work, e.g. is one or the other more flexible about sizes of tensors in run-time?

**Comment by csukuangfj** [comment]
> So what are the differences between jit and onnx?

torchscript models require torch support and can be run only with PyTorch.

ONNX defines a format to record the model structure and parameters. There are various runtimes that support ONNX. See
https://onnxruntime.ai/

Screen Shot 2022-08-03 at 07 36 05

Also, many inference frameworks have their own model format but they provide tools to convert ONNX format
to their own, e.g., [ncnn](https://github.com/Tencent/ncnn), [mace](https://github.com/XiaoMi/mace), etc. They may be highly optimized for a specific hardware architecture.

Moreover, those frameworks support model quantization using their own model format.

In my opinion, supporting ONNX format gives us more flexibility.

**Comment by csukuangfj** [comment]
I only test the non-streaming conformer in this PR.

@yaozengwei  If you want to use it for streaming conformer, you may need to write separate tests for it.

I am going to merge it now.

**Comment by EmreOzkose** [comment]
Hi, should I change onnx_check.py, or create a new file like onnx_check_all_in_one.py ? I made changes in [here](https://github.com/EmreOzkose/icefall/tree/onnx_extract).

1. added onnx all-in-one exporting to [export.py](https://github.com/EmreOzkose/icefall/blob/onnx_extract/egs/librispeech/ASR/pruned_transducer_stateless3/export.py)
2. add [onnx_check_all_in_one.py](https://github.com/EmreOzkose/icefall/blob/onnx_extract/egs/librispeech/ASR/pruned_transducer_stateless3/onnx_check_all_in_one.py)

**Comment by csukuangfj** [comment]
@EmreOzkose 

Thanks! Your changes look great to me. 

Creating a new file `onnx_check_all_in_one.py` is fine (please change the author name to yours).

Could you create a PR?

**Pull request merged**
