### PR TITLE
Narrower and deeper conformer

### PR DESCRIPTION
**Pull request by csukuangfj**
Use a deeper and narrower conformer.

```diff
@@ -322,10 +322,10 @@
             # parameters for conformer
             "feature_dim": 80,
             "subsampling_factor": 4,
-            "encoder_dim": 512,
+            "encoder_dim": 384,
             "nhead": 8,
-            "dim_feedforward": 2048,
-            "num_encoder_layers": 12,
+            "dim_feedforward": 1536,
+            "num_encoder_layers": 24,
             # parameters for decoder
             "decoder_dim": 512,
             # parameters for joiner
```
Comparison of number of model parameters:
- `78648040` (before)
- `88983920` (this PR)

It also uses random combiner from https://github.com/k2-fsa/icefall/pull/229

Closes #269

### CODE REVIEW

**Comment by csukuangfj** [comment]
The training command is
```bash
$ cat run-pruned-rnnt.sh
#!/usr/bin/env bash

export CUDA_VISIBLE_DEVICES="0,1,2,3,4,5,6,7"

. path.sh

./pruned_transducer_stateless4/train.py \
  --world-size 8 \
  --num-epochs 40 \
  --start-epoch 0 \
  --full-libri 1 \
  --exp-dir pruned_transducer_stateless4/exp \
  --max-duration 300 \
  --use-fp16 0
```

Then tensorboard log can be found at https://tensorboard.dev/experiment/f8AtQv0IQy62JrV8Ip4Axg/

**Comment by csukuangfj** [comment]
Here are the results for this PR so far:
```
(py38) kuangfangjun:greedy_search$ grep -r -n --color "best for test-clean" log-* | sort -n -k2 | head
log-decode-epoch-31-avg-17-context-2-max-sym-per-frame-1-2022-04-25-17-59-03:15:greedy_search   2.47    best for test-clean
log-decode-epoch-32-avg-19-context-2-max-sym-per-frame-1-2022-04-25-17-49-09:15:greedy_search   2.47    best for test-clean
log-decode-epoch-31-avg-16-context-2-max-sym-per-frame-1-2022-04-25-17-57-23:15:greedy_search   2.48    best for test-clean
log-decode-epoch-31-avg-18-context-2-max-sym-per-frame-1-2022-04-25-18-00-44:15:greedy_search   2.48    best for test-clean
log-decode-epoch-32-avg-18-context-2-max-sym-per-frame-1-2022-04-25-17-47-21:15:greedy_search   2.49    best for test-clean
log-decode-epoch-32-avg-17-context-2-max-sym-per-frame-1-2022-04-25-17-45-35:15:greedy_search   2.5     best for test-clean
log-decode-epoch-33-avg-17-context-2-max-sym-per-frame-1-2022-04-25-17-29-27:15:greedy_search   2.5     best for test-clean
log-decode-epoch-32-avg-16-context-2-max-sym-per-frame-1-2022-04-25-17-43-42:15:greedy_search   2.51    best for test-clean
log-decode-epoch-33-avg-16-context-2-max-sym-per-frame-1-2022-04-25-17-28-05:15:greedy_search   2.51    best for test-clean
log-decode-epoch-33-avg-19-context-2-max-sym-per-frame-1-2022-04-25-17-33-42:15:greedy_search   2.51    best for test-clean
(py38) kuangfangjun:greedy_search$ grep -r -n --color "best for test-other" log-* | sort -n -k2 | head
log-decode-epoch-33-avg-19-context-2-max-sym-per-frame-1-2022-04-25-17-33-42:23:greedy_search   5.7     best for test-other
log-decode-epoch-31-avg-17-context-2-max-sym-per-frame-1-2022-04-25-17-59-03:23:greedy_search   5.74    best for test-other
log-decode-epoch-32-avg-19-context-2-max-sym-per-frame-1-2022-04-25-17-49-09:23:greedy_search   5.74    best for test-other
log-decode-epoch-33-avg-15-context-2-max-sym-per-frame-1-2022-04-25-17-26-49:23:greedy_search   5.74    best for test-other
log-decode-epoch-31-avg-13-context-2-max-sym-per-frame-1-2022-04-25-17-52-31:23:greedy_search   5.75    best for test-other
log-decode-epoch-32-avg-18-context-2-max-sym-per-frame-1-2022-04-25-17-47-21:23:greedy_search   5.75    best for test-other
log-decode-epoch-32-avg-14-context-2-max-sym-per-frame-1-2022-04-25-17-40-21:23:greedy_search   5.76    best for test-other
log-decode-epoch-32-avg-17-context-2-max-sym-per-frame-1-2022-04-25-17-45-35:23:greedy_search   5.76    best for test-other
log-decode-epoch-33-avg-16-context-2-max-sym-per-frame-1-2022-04-25-17-28-05:23:greedy_search   5.76    best for test-other
log-decode-epoch-33-avg-18-context-2-max-sym-per-frame-1-2022-04-25-17-31-14:23:greedy_search   5.76    best for test-other
```

The decoding command is
```bash
for epoch in 32 31 30 ; do
  for avg in 12 13 14 15 16 17 18 19; do
    ./pruned_transducer_stateless4/decode.py \
      --epoch $epoch \
      --avg $avg \
      --exp-dir ./pruned_transducer_stateless4/exp \
      --max-duration 600 \
      --decoding-method greedy_search \
      --max-sym-per-frame 1
  done
done
```

You can see that the WER for test-clean is below 2.5 for greedy search.

**Comment by danpovey** [comment]
So is this a little better than the regular-shape conformer?

**Comment by csukuangfj** [comment]
> So is this a little better than the regular-shape conformer?

Yes, I am comparing the decoding results for models with a different number of parameters.

**Comment by csukuangfj** [comment]
Here are the results of this PR.

Note that models in `pruned_transducer_stateless` and `pruned_transducer_stateless2` have about 80 M parameters.

The notations `large` and `medium` below are from the [Conformer](https://arxiv.org/pdf/2005.08100.pdf) paper, where the large model has about 118 M parameters and the medium model has 30.8 M parameters.

You can see that using a model with more parameters (i.e., 118 M vs the baseline 80 M) is helpful for the LibriSpeech dataset.

## Large

The number of model parameters is 118129516 (i.e, 118.13 M).

|                                     | test-clean | test-other | comment                                                                       |
|-------------------------------------|------------|------------|----------------------------------------|
| greedy search (max sym per frame 1) | 2.39       | 5.57       | --epoch 39 --avg 7  --max-duration 600 |
| modified beam search                | 2.35       | 5.50       | --epoch 39 --avg 7  --max-duration 600 |
| fast beam search                    | 2.38       | 5.50       | --epoch 39 --avg 7 --max-duration 600  |

```bash
export CUDA_VISIBLE_DEVICES="0,1,2,3,4,5,6,7"

./pruned_transducer_stateless5/train.py \
  --world-size 8 \
  --num-epochs 40 \
  --start-epoch 0 \
  --full-libri 1 \
  --exp-dir pruned_transducer_stateless5/exp-L \
  --max-duration 300 \
  --use-fp16 0 \
  --num-encoder-layers 18 \
  --dim-feedforward 2048 \
  --nhead 8 \
  --encoder-dim 512 \
  --decoder-dim 512 \
  --joiner-dim 512
```

The tensorboard log can be found at
<https://tensorboard.dev/experiment/Zq0h3KpnQ2igWbeR4U82Pw/>

You can find a pretrained model, training logs, decoding logs, and decoding
results at:
<https://huggingface.co/csukuangfj/icefall-asr-librispeech-pruned-transducer-stateless5-2022-05-13>


## Medium

Number of model parameters: 30896748 (i.e, 30.9 M).

|                                     | test-clean | test-other | comment                                                                       |
|-------------------------------------|------------|------------|-----------------------------------------|
| greedy search (max sym per frame 1) | 2.88       | 6.69       | --epoch 39 --avg 17  --max-duration 600 |
| modified beam search                | 2.83       | 6.59       | --epoch 39 --avg 17  --max-duration 600 |
| fast beam search                    | 2.83       | 6.61       | --epoch 39 --avg 17 --max-duration 600  |

```bash
export CUDA_VISIBLE_DEVICES="0,1,2,3,4,5,6,7"

./pruned_transducer_stateless5/train.py \
  --world-size 8 \
  --num-epochs 40 \
  --start-epoch 0 \
  --full-libri 1 \
  --exp-dir pruned_transducer_stateless5/exp-M \
  --max-duration 300 \
  --use-fp16 0 \
  --num-encoder-layers 18 \
  --dim-feedforward 1024 \
  --nhead 4 \
  --encoder-dim 256 \
  --decoder-dim 512 \
  --joiner-dim 512
```

The tensorboard log can be found at
<https://tensorboard.dev/experiment/bOQvULPsQ1iL7xpdI0VbXw/>

You can find a pretrained model, training logs, decoding logs, and decoding
results at:
<https://huggingface.co/csukuangfj/icefall-asr-librispeech-pruned-transducer-stateless5-M-2022-05-13>

**Comment by danpovey** [comment]
Nice!

**Comment by danpovey** [comment]
The baseline, with RandomCombiner, is a bit old, I didn't even realize we had merged that recipe.
Did you ever try this as a modification to pruned_transducer_stateless2?

**Comment by danpovey** [comment]
... I think some comments at the top of this PR are a bit misleading, as they mention using a dim of 384 and also using the RandomCombiner code, neither of which I think you are doing in the end?  Perhaps you could edit them with strikethroughs or some other way of indicating that this is not what we eventually merged, so future people who look at this PR aren't misled?

**Comment by danpovey** [comment]
.. sorry for closing it-- wrong button

**Comment by csukuangfj** [comment]
> The baseline, with RandomCombiner, is a bit old, I didn't even realize we had merged that recipe.

You have merged it in https://github.com/k2-fsa/icefall/pull/229, but later you removed it from your reworked model in some commit.

I created a PR for it https://github.com/k2-fsa/icefall/pull/269
and ran an experiment for the 100 hours subset (test-clean-100).

The exp dir is
`/root/fangjun/open-source-2/icefall-pruned-rnnt-3/egs/librispeech/ASR/pruned_transducer_stateless-2/exp-100`

The results for greedy search are
```
(py38) kuangfangjun:greedy_search$ grep -r -n --color "best for test-clean" log-* | sort -n -k2 | head -n3
log-decode-epoch-29-avg-9-context-2-max-sym-per-frame-1-2022-03-29-15-20-57:15:greedy_search    7.47    best for test-clean
log-decode-epoch-29-avg-8-context-2-max-sym-per-frame-1-2022-03-29-15-20-02:15:greedy_search    7.5     best for test-clean
log-decode-epoch-27-avg-7-context-2-max-sym-per-frame-1-2022-03-29-15-34-04:15:greedy_search    7.51    best for test-clean
(py38) kuangfangjun:greedy_search$ grep -r -n --color "best for test-other" log-* | sort -n -k2 | head -n3
log-decode-epoch-29-avg-8-context-2-max-sym-per-frame-1-2022-03-29-15-20-02:23:greedy_search    19.38   best for test-other
log-decode-epoch-29-avg-9-context-2-max-sym-per-frame-1-2022-03-29-15-20-57:23:greedy_search    19.38   best for test-other
log-decode-epoch-29-avg-10-context-2-max-sym-per-frame-1-2022-03-29-15-21-52:23:greedy_search   19.45   best for test-other
```

which is a bit better than the one you posted in https://github.com/k2-fsa/icefall/pull/229#issue-1153929757
> There is a significant WER improvement from this: on test-clean-100 on this setup i have 7.58/20.36 with greedy search, whereas with similar setups I was more usually getting 8.xx / 22.xx or so.

**Comment by csukuangfj** [comment]
> ... I think some comments at the top of this PR are a bit misleading, as they mention using a dim of 384 and also using the RandomCombiner code, neither of which I think you are doing in the end?

I have results for it, which are also better than the baseline.  

Wait for a few minutes. I will commit them into this PR.

**Comment by csukuangfj** [comment]
Here are the results for the narrower and deeper model.
(Number of model parameters 88983920 (i.e., 88.98 M)

Note that it is better than the baseline. I am running a new experiment with random combiner being removed to verify whether the improvement is due to the random combiner or because of using more layers.

```bash
# training commands
./pruned_transducer_stateless5/train.py \
  --world-size 8 \
  --num-epochs 40 \
  --start-epoch 34 \
  --full-libri 1 \
  --exp-dir pruned_transducer_stateless5/exp \
  --max-duration 300 \
  --use-fp16 0 \
  --num-encoder-layers 24 \
  --dim-feedforward 1536 \
  --nhead 8 \
  --encoder-dim 384 \
  --decoder-dim 512 \
  --joiner-dim 512
```

| method | test-clean | test-other|
|--------|-----------|----------|
|greedy search|  2.41 | 5.70 |
|modified beam search| 2.41 | 5.69|
|fast beam search | 2.41 | 5.69|

Results are available at
```
/root/fangjun/open-source-2/icefall-deeper-conformer/egs/librispeech/ASR/pruned_transducer_stateless5/exp
```


Decoding commands are
```bash
for epoch in 31; do
  for avg in 17; do
    for m in greedy_search modified_beam_search fast_beam_search; do
      ./pruned_transducer_stateless5/decode.py \
        --epoch $epoch \
        --avg $avg \
        --exp-dir ./pruned_transducer_stateless5/exp \
        --max-duration 600 \
        --decoding-method $m \
        --max-sym-per-frame 1 \
        --num-encoder-layers 24 \
        --dim-feedforward 1536 \
        --nhead 8 \
        --encoder-dim 384 \
        --decoder-dim 512 \
        --joiner-dim 512
      done
  done
done
```

**Comment by csukuangfj** [comment]
Here are the results for this PR.

It shows:
(1) Increasing the number of layers improves the results. 
(2) Using a narrower but deeper model also helps.
(3) Models with random combiner are slightly better. @danpovey  Shall we keep or remove random combiner?

## Without random combiner

|num parameters | num encoder layers | dim feedforward | num heads |  encoder dim | greedy search | modified beam search | fast beam search | comment | pretrained model link and training logs|
|----|----|----|-----|-----|----|----|----|---|---|
|78.65M(baseline, #288)| 12 | 2048|8|512|2.62/6.03|2.59/6.19|2.57/5.95| #288 | |
|87.8M| 24 | 1536 | 8 |  384 | 2.48/5.80 | 2.45/5.72 |  2.45/5.71| --epoch 34 --avg 19 | https://huggingface.co/csukuangfj/icefall-asr-librispeech-pruned-transducer-stateless5-narrower-2022-05-23|
|30.5M| 18 | 1024 |4| 256| 2.82/6.99|2.78/6.82|2.77/6.91|--epoch 39 --avg 6| https://huggingface.co/csukuangfj/icefall-asr-librispeech-pruned-transducer-stateless5-M-2022-05-23 |
|116.55M|18|2048|8|512|2.42/5.77|2.39/5.73|2.39/5.73|--epoch 39 --avg 13 | https://huggingface.co/csukuangfj/icefall-asr-librispeech-pruned-transducer-stateless5-L-2022-05-23|

## With random combiner

|num parameters | num encoder layers | dim feedforward | num heads |  encoder dim | greedy search | modified beam search | fast beam search | comment | pretrained model link and training logs|
|----|----|----|-----|-----|----|----|----|---|---|
|88.98M|24 |1536 |8|384|2.41/5.70| 2.41/5.69| 2.41/5.69| --epoch 31 --avg 17|https://huggingface.co/csukuangfj/icefall-asr-librispeech-pruned-transducer-stateless5-narrower-2022-05-13|
|30.9M|18|1024|4|256|2.88/6.69|2.83/6.59|2.83/6.61|--epoch 39 --avg 17 | https://huggingface.co/csukuangfj/icefall-asr-librispeech-pruned-transducer-stateless5-M-2022-05-13|
|118.13M|18|2048|8|512|2.39/5.57|2.35/5.50|2.38/5.50|--epoch 39 --avg 7|https://huggingface.co/csukuangfj/icefall-asr-librispeech-pruned-transducer-stateless5-2022-05-13|

**Comment by danpovey** [comment]
Ah, OK.  Yes I suppose you are right, we should keep the random combiner.
Notice it has layers that you can choose to combine, I think those are configurable, it may be worth tuning that, and any other parameters it has.  But that can be done in future.

**Comment by csukuangfj** [comment]
I have added random-combiner back.

 Merging.

**Pull request merged**
