### PR TITLE
Combining rnnt loss and k2-ctc loss for Dan's Zipformer

### PR DESCRIPTION
**Pull request by yaozengwei**
Following https://github.com/k2-fsa/icefall/pull/477, this PR combines rnnt loss and k2-ctc loss to train Dan's Zipformer(see https://github.com/k2-fsa/icefall/pull/672). It has following advantages: 

- Adding ctc branch can slightly improve the performance of the rnnt branch, at the cost of negligible extra computation for ctc loss. 
- We can also get promising decoding results from the ctc branch. (See https://github.com/k2-fsa/icefall/pull/477#issuecomment-1311500125). Benefitting from high efficiency of the pruned rnnt loss, I think this strategy is preferable than combining ctc with attention decoder, which leads to more parameters and lower computation efficiency.

### CODE REVIEW

**Comment by yaozengwei** [comment]
I train the models on train-clean-100 for 30 epochs, and get the following results from the rnnt branch and ctc branch. 

<div class="okr-block-clipboard" data-okr="%7B%22okrDelta%22%3A%5B%7B%22lineType%22%3A%22unsupport%22%2C%22lineOptions%22%3A%7B%7D%2C%22lineContent%22%3A%5B%5D%7D%5D%2C%22businessKey%22%3A%22lark-doc%22%7D"></div><div data-zone-id="0" data-line-index="0" style="white-space: pre;">

method | rnnt-greedy-search | comment | ctc-decoding | comment
-- | -- | -- | -- | --
baseline | 6.0 & 15.85 | epoch-30-avg-13 |   |  
ctc-scale=0.2 | 5.85 & **15.5** | epoch-30-avg-13 | 6.53 & 17.41 | epoch-30-avg-13
ctc-scale=0.3 | 5.85 & 15.53 | epoch-30-avg-15 | 6.53 & **17.29** | epoch-30-avg-12
ctc-scale=0.4 | **5.81** & 15.58 | epoch-30-avg-15 | 6.49 & **17.29** | epoch-30-avg-11
ctc-scale=0.5 | 5.89 & 15.77 | epoch-30-avg-13 | **6.46** & 17.4 | epoch-30-avg-13

</div>

**Comment by wangtiance** [comment]
Interesting result! I'd suppose the WER using ctc decoding is also better than training with ctc loss alone (with the same encoder)?

**Comment by yaozengwei** [comment]
> Interesting result! I'd suppose the WER using ctc decoding is also better than training with ctc loss alone (with the same encoder)?

I think so. I will show the decoding result when training with only the ctc loss.

**Comment by kobenaxie** [comment]
> > Interesting result! I'd suppose the WER using ctc decoding is also better than training with ctc loss alone (with the same encoder)?
> 
> I think so. I will show the decoding result when training with only the ctc loss.

probably yes, both tasks may benefit form multi-task training generally.

**Comment by yaozengwei** [comment]
I have added the ctc-decoding result of the model trained with only the ctc loss in the above table.

**Comment by yaozengwei** [comment]
The following two tables present decoding results while training the models on full librispeeh. 

- rnnt branch

<div class="okr-block-clipboard" data-okr="%7B%22okrDelta%22%3A%5B%7B%22lineType%22%3A%22unsupport%22%2C%22lineOptions%22%3A%7B%7D%2C%22lineContent%22%3A%5B%5D%7D%5D%2C%22businessKey%22%3A%22lark-doc%22%7D"></div><div data-zone-id="0" data-line-index="0" style="white-space: pre;">

method | greedy-search | modified-beam-search | fast-beam-search | Comment
-- | -- | -- | -- | --
rnnt | 2.17 & 5.23 | **2.15** & 5.2 | **2.15** & 5.22 | epoch-30-avg-9
rnnt+0.2*ctc | 2.23 & 5.19 | 2.21 & **5.12** | 2.23 & 5.18 | epoch-30-avg-8

- ctc branch
<div class="okr-block-clipboard" data-okr="%7B%22okrDelta%22%3A%5B%7B%22lineType%22%3A%22unsupport%22%2C%22lineOptions%22%3A%7B%7D%2C%22lineContent%22%3A%5B%5D%7D%5D%2C%22businessKey%22%3A%22lark-doc%22%7D"></div><div data-zone-id="0" data-line-index="0" style="white-space: pre;">

method | ctc-decoding | 1best | nbest | nbest-rescoring | whole-lattice-rescoring | Comment
-- | -- | -- | -- | -- | -- | --
rnnt+0.2*ctc | 2.48 & 5.82 | 2.43 & 5.22 | 2.44 & 5.21 | 2.34 & 5.1 | **2.33** & **5.05** | epoch-30-avg-9

</div>

</div>

**Review by csukuangfj — APPROVED** [review]

**Pull request merged**
