### PR TITLE
Fix loading sampler state dict.

### PR DESCRIPTION
**Pull request by csukuangfj**
Fixes https://github.com/lhotse-speech/lhotse/issues/747

The code was written before lhotse fixed the issue in https://github.com/k2-fsa/icefall/pull/314#issuecomment-1104665165

See https://github.com/lhotse-speech/lhotse/pull/684 and https://github.com/lhotse-speech/lhotse/pull/692

### CODE REVIEW

**Comment by danpovey** [comment]
Now it seems to do to many batches, it does not stop after 100 batches or so as it should.
My lhotse version is 1.3.0.dev+git.4198446.clean.
It does load the state dict:
 2022-06-16 10:49:11,380 INFO [asr_datamodule.py:327] Loading sampler state dict
The sampler state_dict looks like this:
```
{'epoch': 13, 'drop_last': True, 'world_size': 1, 'rank': 0, 'seed': 0, 'shuffle': True, 'diagnostics': {'current_epoch': 13, 'stats_per_epoch': {0: {'epoch': 0, 'kept_cuts': 85310, 'discarded_cuts': 0, 'kept_batches': 3723, 'discarded_batches': 0}, 13: {'epoch': 13, 'kept_cuts': 83079, 'discarded_cuts': 0, 'kept_batches': 3625, 'discarded_batches': 0}}}, 'max_duration': 300, 'max_cuts': None, 'consistent_ids': True, 'buffer_size': 10000, 'num_cuts_for_bins_estimate': 10000, 'shuffle_buffer_size': 20000, 'strict': True}
```

**Comment by csukuangfj** [comment]
@pzelasko 
Could you please have a look at it?

**Comment by pzelasko** [comment]
Sure. I’ll take a fresh look tomorrow, I’m a little tired today.

**Comment by csukuangfj** [comment]
>  I suggest to pick one of three solutions (my top pick is 1):

I also prefer the first option. Will make a change later.

**Comment by csukuangfj** [comment]
Thanks to @zzzacwork for testing it.

**Pull request merged**
