### PR TITLE
Add LSTM for the multi-dataset setup.

### PR DESCRIPTION
**Pull request by csukuangfj**
Used ScaledLSTM from #479.

Current results:

```
(py38) kuangfangjun:greedy_search$ grep -r -n --color "best for test-clean" log-* | sort -n -k2 | head -n 5
log-decode-epoch-13-avg-2-context-2-max-sym-per-frame-1-use-averaged-model-2022-08-29-10-35-19:17:greedy_search 2.93    best for test-clean
log-decode-epoch-13-avg-3-context-2-max-sym-per-frame-1-use-averaged-model-2022-08-29-10-36-34:17:greedy_search 2.93    best for test-clean
log-decode-iter-286000-avg-6-context-2-max-sym-per-frame-1-use-averaged-model-2022-08-27-23-51-34:17:greedy_search      2.94    best for test-clean
log-decode-epoch-12-avg-1-context-2-max-sym-per-frame-1-use-averaged-model-2022-08-28-17-30-38:17:greedy_search 2.96    best for test-clean
log-decode-epoch-12-avg-2-context-2-max-sym-per-frame-1-use-averaged-model-2022-08-28-17-31-57:17:greedy_search 2.96    best for test-clean
```

```
(py38) kuangfangjun:modified_beam_search$ grep -r -n --color "best for test-clean" log-* | sort -n -k2 | head -n 5
log-decode-epoch-13-avg-2-modified_beam_search-beam-size-4-use-averaged-model-2022-08-29-10-48-08:18:beam_size_4        2.85    best for test-clean
log-decode-epoch-13-avg-3-modified_beam_search-beam-size-4-use-averaged-model-2022-08-29-10-52-27:18:beam_size_4        2.88    best for test-clean
log-decode-epoch-12-avg-1-modified_beam_search-beam-size-4-use-averaged-model-2022-08-28-17-40-19:18:beam_size_4        2.89    best for test-clean
log-decode-iter-346000-avg-10-modified_beam_search-beam-size-4-use-averaged-model-2022-08-29-11-00-41:18:beam_size_4    2.89    best for test-clean
log-decode-epoch-12-avg-3-modified_beam_search-beam-size-4-use-averaged-model-2022-08-28-17-49-09:18:beam_size_4        2.9     best for test-clean
```

```
(py38) kuangfangjun:fast_beam_search$ grep -r -n --color "best for test-clean" log-* | sort -n -k2 | head -n 5
log-decode-iter-306000-avg-12-beam-4.0-max-contexts-4-max-states-8-use-averaged-model-2022-08-28-13-43-08:18:beam_4.0_max_contexts_4_max_states_8    2.88    best for test-clean
log-decode-iter-308000-avg-13-beam-4.0-max-contexts-4-max-states-8-use-averaged-model-2022-08-28-13-15-06:18:beam_4.0_max_contexts_4_max_states_8    2.89    best for test-clean
log-decode-iter-308000-avg-14-beam-4.0-max-contexts-4-max-states-8-use-averaged-model-2022-08-28-13-19-38:18:beam_4.0_max_contexts_4_max_states_8    2.89    best for test-clean
log-decode-epoch-13-avg-3-beam-4.0-max-contexts-4-max-states-8-use-averaged-model-2022-08-29-10-41-46:18:beam_4.0_max_contexts_4_max_states_8        2.9     best for test-clean
log-decode-iter-302000-avg-9-beam-4.0-max-contexts-4-max-states-8-use-averaged-model-2022-08-28-14-35-27:18:beam_4.0_max_contexts_4_max_states_8     2.9     best for test-clean
```

---

```
(py38) kuangfangjun:greedy_search$ grep -r -n --color "best for test-other" log-* | sort -n -k2 | head -n 5
log-decode-epoch-13-avg-3-context-2-max-sym-per-frame-1-use-averaged-model-2022-08-29-10-36-34:26:greedy_search 7.68    best for test-other
log-decode-iter-348000-avg-12-context-2-max-sym-per-frame-1-use-averaged-model-2022-08-29-11-39-15:26:greedy_search     7.69    best for test-other
log-decode-epoch-13-avg-2-context-2-max-sym-per-frame-1-use-averaged-model-2022-08-29-10-35-19:26:greedy_search 7.7     best for test-other
log-decode-iter-346000-avg-7-context-2-max-sym-per-frame-1-use-averaged-model-2022-08-29-10-34-47:26:greedy_search      7.71    best for test-other
log-decode-iter-348000-avg-11-context-2-max-sym-per-frame-1-use-averaged-model-2022-08-29-11-38-00:26:greedy_search     7.73    best for test-other
```

```
(py38) kuangfangjun:modified_beam_search$ grep -r -n --color "best for test-other" log-* | sort -n -k2 | head -n 5
log-decode-iter-348000-avg-12-modified_beam_search-beam-size-4-use-averaged-model-2022-08-29-12-08-39:28:beam_size_4    7.48    best for test-other
log-decode-iter-348000-avg-9-modified_beam_search-beam-size-4-use-averaged-model-2022-08-29-11-55-08:28:beam_size_4     7.49    best for test-other
log-decode-iter-346000-avg-8-modified_beam_search-beam-size-4-use-averaged-model-2022-08-29-10-52-03:28:beam_size_4     7.51    best for test-other
log-decode-iter-348000-avg-11-modified_beam_search-beam-size-4-use-averaged-model-2022-08-29-12-04-20:28:beam_size_4    7.51    best for test-other
log-decode-iter-348000-avg-8-modified_beam_search-beam-size-4-use-averaged-model-2022-08-29-11-50-19:28:beam_size_4     7.52    best for test-other
```

```
(py38) kuangfangjun:fast_beam_search$ grep -r -n --color "best for test-other" log-* | sort -n -k2 | head -n 5
log-decode-iter-346000-avg-10-beam-4.0-max-contexts-4-max-states-8-use-averaged-model-2022-08-29-10-45-43:28:beam_4.0_max_contexts_4_max_states_8    7.61    best for test-other
log-decode-iter-348000-avg-11-beam-4.0-max-contexts-4-max-states-8-use-averaged-model-2022-08-29-11-46-18:28:beam_4.0_max_contexts_4_max_states_8    7.62    best for test-other
log-decode-epoch-13-avg-1-beam-4.0-max-contexts-4-max-states-8-use-averaged-model-2022-08-29-10-37-48:28:beam_4.0_max_contexts_4_max_states_8        7.63    best for test-other
log-decode-iter-348000-avg-12-beam-4.0-max-contexts-4-max-states-8-use-averaged-model-2022-08-29-11-48-14:28:beam_4.0_max_contexts_4_max_states_8    7.63    best for test-other
log-decode-epoch-13-avg-3-beam-4.0-max-contexts-4-max-states-8-use-averaged-model-2022-08-29-10-41-46:28:beam_4.0_max_contexts_4_max_states_8        7.65    best for test-other
```

### CODE REVIEW

**Comment by csukuangfj** [comment]
Note: Compared to the results of the streaming conformer model from 
https://github.com/k2-fsa/icefall/blob/master/egs/librispeech/ASR/RESULTS.md#training-on-full-librispeech-use-giga_prob--09

ScaledLSTM has competitive (or even better results) for the low latency setup compared against the streaming conformer.

Screen Shot 2022-08-29 at 7 11 29 PM

---

Training command of this PR:
```bash
#!/usr/bin/env bash

export CUDA_VISIBLE_DEVICES="0,1,2,3,4,5,6,7"

./lstm_transducer_stateless2/train.py \
  --world-size 8 \
  --num-epochs 35 \
  --start-epoch 10 \
  --full-libri 1 \
  --exp-dir lstm_transducer_stateless2/exp \
  --max-duration 500 \
  --use-fp16 0 \
  --lr-epochs 10 \
  --num-workers 2 \
  --giga-prob 0.9
```

Decoding command:
```bash
#!/usr/bin/env bash

export CUDA_VISIBLE_DEVICES="0"

for m in greedy_search fast_beam_search modified_beam_search; do
  for epoch in 13; do
    for avg in 1 2 3; do
      ./lstm_transducer_stateless2/decode.py \
        --epoch $epoch \
        --avg $avg \
        --exp-dir lstm_transducer_stateless2/exp \
        --max-duration 600 \
        --num-encoder-layers 12 \
        --rnn-hidden-size 1024 \
        --decoding-method $m \
        --use-averaged-model True \
        --beam 4 \
        --max-contexts 4 \
        --max-states 8 \
        --beam-size 4
    done
  done
done
```

**Comment by danpovey** [comment]
Cool!
I am hoping that after fixing gradient explosion issues, we can further improve these results.

**Comment by csukuangfj** [comment]
Here are the results after training for more epochs (at epoch 16):

The WER for test-clean is 2.76.  I think it will continue to decrease after training for more epochs.

Screen Shot 2022-08-31 at 2 32 53 PM


Screen Shot 2022-08-31 at 2 34 17 PM

**Comment by csukuangfj** [comment]
Results for this PR:

|                                     | test-clean | test-other | comment                 |
|-------------------------------------|------------|------------|-------------------------|
| greedy search (max sym per frame 1) | 2.78       | 7.36       | --iter 468000 --avg 16  |
| modified_beam_search                | **2.73**       | 7.15       | --iter 468000 --avg 16  |
| fast_beam_search                    | 2.76       | 7.31       | --iter 468000 --avg 16  |
| greedy search (max sym per frame 1) | 2.77       | 7.35       | --iter 472000 --avg 18  |
| modified_beam_search                | 2.75       | **7.08**       | --iter 472000 --avg 18  |
| fast_beam_search                    | 2.77       | 7.29       | --iter 472000 --avg 18  |

We use `--iter` rather than `--epoch` since `--iter` produces better results in this case.

The model is trained for 18 epochs.

---

The training command is:

```bash
export CUDA_VISIBLE_DEVICES="0,1,2,3,4,5,6,7"

./lstm_transducer_stateless2/train.py \
  --world-size 8 \
  --num-epochs 35 \
  --start-epoch 1 \
  --full-libri 1 \
  --exp-dir lstm_transducer_stateless2/exp \
  --max-duration 500 \
  --use-fp16 0 \
  --lr-epochs 10 \
  --num-workers 2 \
  --giga-prob 0.9
```
**Note**: It was killed manually after getting `epoch-18.pt`. Also, we resumed
training after getting `epoch-9.pt`.

The tensorboard log can be found at
<https://tensorboard.dev/experiment/1ziQ2LFmQY2mt4dlUr5dyA/>

The decoding command is
```bash
for m in greedy_search fast_beam_search modified_beam_search; do
  for iter in 472000; do
    for avg in 8 10 12 14 16 18; do
      ./lstm_transducer_stateless2/decode.py \
        --iter $iter \
        --avg $avg \
        --exp-dir lstm_transducer_stateless2/exp \
        --max-duration 600 \
        --num-encoder-layers 12 \
        --rnn-hidden-size 1024 \
        --decoding-method $m \
        --use-averaged-model True \
        --beam 4 \
        --max-contexts 4 \
        --max-states 8 \
        --beam-size 4
    done
  done
done
```

Pretrained models, training logs, decoding logs, and decoding results
are available at
<https://huggingface.co/csukuangfj/icefall-asr-librispeech-lstm-transducer-stateless2-2022-09-03>

**Comment by danpovey** [comment]
Nice!!  Could you or @yaozengwei please run with --diagnostics=True with this model?  I want to see whether the gradients are blowing up.

**Comment by danpovey** [comment]
I have been looking at the diagnostics file that we got on epoch 18 from running with --print-diagnostics=True.
It seems that gradient explosion is only happening in one layer: layer number 10.  Very possibly this is normal,
we don't have very much to compare it with right now.
Firstly, all the layers' lstm and feed_forward modules have output that is of roughly the same magnitude, generally between 0.1 and 0.4 as rms value.  So we can compare the gradient magnitudes without worrying that the real importance of
the layer's output needs to be adjusted for the output magnitude.

At the output of the lstm layers, the grad is dramatically bigger for layers 9 and below, by a factor
of about 2000.  (it's a bit smaller for layers 3 and 4, about half of the usual, but we can ignore that 
for now.. maybe it was relying more on the feedforward module on those layers.)
```
grep 'lstm.grad\[0\]' diagnostics-start-from-epoch-18.txt | grep 'dim=2' | grep 'rms '
module=encoder.encoder.layers.0.lstm.grad[0], dim=2, size=512, rms percentiles: [1.5e+02 1.9e+02 1.9e+02 2e+02 2.1e+02 2.1e+02 2.2e+02 2.3e+02 2.4e+02 2.6e+02 4.9e+02], mean=2.2e+02, rms=2.2e+02
module=encoder.encoder.layers.1.lstm.grad[0], dim=2, size=512, rms percentiles: [1.2e+02 1.6e+02 1.6e+02 1.7e+02 1.8e+02 1.8e+02 1.9e+02 2e+02 2.1e+02 2.2e+02 3.8e+02], mean=1.9e+02, rms=1.9e+02
module=encoder.encoder.layers.2.lstm.grad[0], dim=2, size=512, rms percentiles: [17 20 21 22 23 23 24 25 26 28 46], mean=24, rms=24
module=encoder.encoder.layers.3.lstm.grad[0], dim=2, size=512, rms percentiles: [16 19 20 21 21 22 23 24 25 27 38], mean=23, rms=23
module=encoder.encoder.layers.4.lstm.grad[0], dim=2, size=512, rms percentiles: [1.2e+02 1.5e+02 1.6e+02 1.6e+02 1.7e+02 1.7e+02 1.8e+02 1.9e+02 1.9e+02 2.1e+02 2.7e+02], mean=1.8e+02, rms=1.8e+02
module=encoder.encoder.layers.5.lstm.grad[0], dim=2, size=512, rms percentiles: [1.2e+02 1.4e+02 1.5e+02 1.6e+02 1.6e+02 1.7e+02 1.7e+02 1.8e+02 1.9e+02 2e+02 2.6e+02], mean=1.7e+02, rms=1.7e+02
module=encoder.encoder.layers.6.lstm.grad[0], dim=2, size=512, rms percentiles: [1.1e+02 1.3e+02 1.4e+02 1.4e+02 1.5e+02 1.5e+02 1.6e+02 1.7e+02 1.7e+02 1.8e+02 2.3e+02], mean=1.6e+02, rms=1.6e+02
module=encoder.encoder.layers.7.lstm.grad[0], dim=2, size=512, rms percentiles: [1.2e+02 1.5e+02 1.5e+02 1.6e+02 1.7e+02 1.7e+02 1.8e+02 1.8e+02 1.9e+02 2e+02 2.5e+02], mean=1.7e+02, rms=1.7e+02
module=encoder.encoder.layers.8.lstm.grad[0], dim=2, size=512, rms percentiles: [1e+02 1.2e+02 1.3e+02 1.3e+02 1.3e+02 1.4e+02 1.4e+02 1.5e+02 1.5e+02 1.6e+02 2e+02], mean=1.4e+02, rms=1.4e+02
module=encoder.encoder.layers.9.lstm.grad[0], dim=2, size=512, rms percentiles: [85 1e+02 1.1e+02 1.2e+02 1.2e+02 1.2e+02 1.3e+02 1.3e+02 1.3e+02 1.4e+02 2.3e+02], mean=1.2e+02, rms=1.2e+02
module=encoder.encoder.layers.10.lstm.grad[0], dim=2, size=512, rms percentiles: [0.036 0.046 0.048 0.049 0.051 0.052 0.054 0.056 0.058 0.063 0.23], mean=0.054, rms=0.055
module=encoder.encoder.layers.11.lstm.grad[0], dim=2, size=512, rms percentiles: [0.042 0.048 0.05 0.053 0.056 0.058 0.061 0.064 0.07 0.077 0.59], mean=0.062, rms=0.067
```
The same is true of the gradients w.r.t. the feedforward modules.  If we look at the param grads, layer 11 has about 100 times smaller magnitude than most layers, but layer 10 actually has the largest param grad, about 10 times the normal value.  This confirms that the gradient explosion is happening in layer 10, which is in fact the only place where it could be happening given the previous things I noticed.
```
grep 'lstm.weight_hh_l0.param_grad' diagnostics-start-from-epoch-18.txt | grep 'dim=1' | grep 'rms '
module=encoder.encoder.layers.0.lstm.weight_hh_l0.param_grad, dim=1, size=512, rms percentiles: [1e+02 1.4e+02 1.6e+02 1.8e+02 2e+02 2.2e+02 2.5e+02 2.9e+02 3.4e+02 4.1e+02 8.6e+02], mean=2.6e+02, rms=2.8e+02
module=encoder.encoder.layers.1.lstm.weight_hh_l0.param_grad, dim=1, size=512, rms percentiles: [53 80 90 1e+02 1.1e+02 1.3e+02 1.4e+02 1.6e+02 1.9e+02 2.3e+02 6.8e+02], mean=1.4e+02, rms=1.6e+02
module=encoder.encoder.layers.2.lstm.weight_hh_l0.param_grad, dim=1, size=512, rms percentiles: [9.4 17 20 23 26 29 32 38 44 54 90], mean=33, rms=36
module=encoder.encoder.layers.3.lstm.weight_hh_l0.param_grad, dim=1, size=512, rms percentiles: [7.7 12 13 15 16 17 18 20 22 25 1.2e+02], mean=18, rms=20
module=encoder.encoder.layers.4.lstm.weight_hh_l0.param_grad, dim=1, size=512, rms percentiles: [90 1.4e+02 1.6e+02 1.8e+02 2.1e+02 2.4e+02 2.8e+02 3.3e+02 3.9e+02 4.6e+02 1.1e+03], mean=2.8e+02, rms=3.2e+02
module=encoder.encoder.layers.5.lstm.weight_hh_l0.param_grad, dim=1, size=512, rms percentiles: [59 85 95 1.1e+02 1.2e+02 1.3e+02 1.4e+02 1.6e+02 1.8e+02 2.2e+02 4.5e+02], mean=1.4e+02, rms=1.6e+02
module=encoder.encoder.layers.6.lstm.weight_hh_l0.param_grad, dim=1, size=512, rms percentiles: [1.1e+02 1.6e+02 1.8e+02 2e+02 2.2e+02 2.4e+02 2.8e+02 3.2e+02 3.8e+02 4.8e+02 1.1e+03], mean=2.9e+02, rms=3.2e+02
module=encoder.encoder.layers.7.lstm.weight_hh_l0.param_grad, dim=1, size=512, rms percentiles: [59 97 1.1e+02 1.3e+02 1.4e+02 1.7e+02 1.9e+02 2.2e+02 2.5e+02 3.2e+02 5.6e+02], mean=1.9e+02, rms=2.1e+02
module=encoder.encoder.layers.8.lstm.weight_hh_l0.param_grad, dim=1, size=512, rms percentiles: [1.8e+02 2.8e+02 3.3e+02 3.8e+02 4.2e+02 4.7e+02 5.3e+02 6.1e+02 7.1e+02 8.2e+02 1.6e+03], mean=5.2e+02, rms=5.7e+02
module=encoder.encoder.layers.9.lstm.weight_hh_l0.param_grad, dim=1, size=512, rms percentiles: [1.4e+02 2.3e+02 2.8e+02 3.3e+02 3.7e+02 4.5e+02 5.4e+02 6.4e+02 7.5e+02 9.6e+02 1.5e+03], mean=5.3e+02, rms=6e+02
module=encoder.encoder.layers.10.lstm.weight_hh_l0.param_grad, dim=1, size=512, rms percentiles: [7.9e+02 1.2e+03 1.4e+03 1.5e+03 1.7e+03 1.9e+03 2.2e+03 2.5e+03 2.9e+03 3.5e+03 6.8e+03], mean=2.2e+03, rms=2.4e+03
module=encoder.encoder.layers.11.lstm.weight_hh_l0.param_grad, dim=1, size=512, rms percentiles: [0.27 0.46 0.56 0.67 0.79 0.93 1.1 1.3 1.5 1.9 11], mean=1.1, rms=1.3
```

**Comment by danpovey** [comment]
Something else: if we look at the stats over the batch dim, we can see whether some elements of the batch have larger gradients than others.  Normally these distributions would be very flat, but here they are not, the last element in the list is enormously larger, meaning a small number of sequences have 1000 times larger gradient.  You can see that this does not happen for layers 10 and 11 (this is measured at the output of the lstm module); it only happens for layers prior to 10.
```
grep 'lstm.grad\[0\]' diagnostics-start-from-epoch-18.txt | grep 'dim=1' | grep 'rms '
module=encoder.encoder.layers.0.lstm.grad[0], dim=1, size=5..51, rms percentiles: [0.071 0.18 0.23 0.27 0.33 0.37 0.47 0.61 0.88 1.7 1.1e+03], mean=9.3, rms=89
module=encoder.encoder.layers.1.lstm.grad[0], dim=1, size=5..51, rms percentiles: [0.049 0.14 0.16 0.19 0.23 0.26 0.34 0.44 0.65 1.2 9.2e+02], mean=7.8, rms=76
module=encoder.encoder.layers.2.lstm.grad[0], dim=1, size=5..51, rms percentiles: [0.042 0.12 0.14 0.16 0.19 0.22 0.25 0.32 0.44 0.97 1e+02], mean=1.6, rms=9.7
module=encoder.encoder.layers.3.lstm.grad[0], dim=1, size=5..51, rms percentiles: [0.0074 0.1 0.12 0.14 0.17 0.19 0.22 0.28 0.4 0.73 1.1e+02], mean=1.3, rms=9.2
module=encoder.encoder.layers.4.lstm.grad[0], dim=1, size=5..51, rms percentiles: [0.014 0.081 0.11 0.13 0.16 0.18 0.21 0.3 0.48 1 8.5e+02], mean=7.3, rms=71
module=encoder.encoder.layers.5.lstm.grad[0], dim=1, size=5..51, rms percentiles: [0.045 0.091 0.11 0.12 0.15 0.16 0.2 0.29 0.45 0.93 8.2e+02], mean=6.6, rms=68
module=encoder.encoder.layers.6.lstm.grad[0], dim=1, size=5..51, rms percentiles: [0.046 0.082 0.094 0.11 0.13 0.14 0.17 0.25 0.39 0.92 7.3e+02], mean=6.5, rms=63
module=encoder.encoder.layers.7.lstm.grad[0], dim=1, size=5..51, rms percentiles: [0.011 0.067 0.093 0.11 0.13 0.15 0.17 0.21 0.36 0.86 8.2e+02], mean=7.1, rms=69
module=encoder.encoder.layers.8.lstm.grad[0], dim=1, size=5..51, rms percentiles: [0.0079 0.035 0.066 0.076 0.092 0.11 0.13 0.18 0.28 0.6 6.9e+02], mean=5.7, rms=57
module=encoder.encoder.layers.9.lstm.grad[0], dim=1, size=5..51, rms percentiles: [0.033 0.054 0.066 0.076 0.087 0.1 0.11 0.18 0.27 0.71 6.3e+02], mean=5.1, rms=50
module=encoder.encoder.layers.10.lstm.grad[0], dim=1, size=5..51, rms percentiles: [0.0024 0.02 0.025 0.027 0.033 0.039 0.046 0.052 0.062 0.074 0.17], mean=0.044, rms=0.052
module=encoder.encoder.layers.11.lstm.grad[0], dim=1, size=5..51, rms percentiles: [0.016 0.032 0.035 0.039 0.042 0.047 0.052 0.057 0.068 0.087 0.21], mean=0.055, rms=0.061
```
Because the batch sizes vary, in effect the diagnostics code just appends the batch-sizes over all the batches, rather than trying to correlate those dims somehow.  So this is telling us that some sequences have blown-up gradients but most sequences are fine.

**Comment by danpovey** [comment]
Zengwei is using the "gradient filter" idea from #564, which zeroes out the gradients from any sequences that seem to have a way-too-large gradient, doing this at the input of the LSTM layer.  He is continuing Fangjun's training run from here, but from epoch 19.
It seems to resolve the huge-gradient issue.  Running with a threshold of 10.0, meaning that sequences with a more than 10x-larger-than-median gradient have their gradient zeroed, we see the following gradient sizes; the rms value is about 200 times larger than before.

The loss function is also very promising.  Fangjun's model at epoch 18 had its tot_loss at around 0.20; ours seems to be oscillating between about 0.165 and 0.185 so far.

grep 'lstm.grad\[0\]' /ceph-zw/workspace/rnn/icefall_multi_dataset/egs/librispeech/ASR/lstm_transducer_stateless3/exp-threshold-10.0/diagnostics-epoch-19  | grep 'dim=1' | grep 'rms '  
```
module=encoder.encoder.layers.0.lstm.grad[0], dim=1, size=5..51, rms percentiles: [0.04 0.13 0.17 0.19 0.22 0.25 0.29 0.36 0.47 0.67 1.5], mean=0.34, rms=0.42
module=encoder.encoder.layers.1.lstm.grad[0], dim=1, size=5..51, rms percentiles: [0.031 0.097 0.12 0.13 0.15 0.18 0.21 0.26 0.34 0.51 1.2], mean=0.25, rms=0.31
module=encoder.encoder.layers.10.lstm.grad[0], dim=1, size=5..51, rms percentiles: [0.0025 0.022 0.026 0.029 0.032 0.038 0.044 0.049 0.062 0.072 0.17], mean=0.044, rms=0.051
module=encoder.encoder.layers.11.lstm.grad[0], dim=1, size=5..51, rms percentiles: [0.018 0.031 0.034 0.038 0.041 0.044 0.049 0.056 0.069 0.087 0.21], mean=0.054, rms=0.061
module=encoder.encoder.layers.2.lstm.grad[0], dim=1, size=5..51, rms percentiles: [0.028 0.089 0.11 0.12 0.14 0.16 0.17 0.2 0.26 0.33 0.74], mean=0.19, rms=0.22
module=encoder.encoder.layers.3.lstm.grad[0], dim=1, size=5..51, rms percentiles: [0.0078 0.066 0.092 0.11 0.12 0.14 0.15 0.18 0.23 0.3 0.98], mean=0.17, rms=0.23
module=encoder.encoder.layers.4.lstm.grad[0], dim=1, size=5..51, rms percentiles: [0.014 0.062 0.081 0.093 0.1 0.12 0.13 0.16 0.21 0.3 1], mean=0.16, rms=0.21
module=encoder.encoder.layers.5.lstm.grad[0], dim=1, size=5..51, rms percentiles: [0.023 0.07 0.083 0.093 0.1 0.11 0.13 0.15 0.19 0.26 1.3], mean=0.16, rms=0.21
module=encoder.encoder.layers.6.lstm.grad[0], dim=1, size=5..51, rms percentiles: [0.021 0.062 0.072 0.079 0.088 0.099 0.11 0.13 0.17 0.24 1.7], mean=0.14, rms=0.19
module=encoder.encoder.layers.7.lstm.grad[0], dim=1, size=5..51, rms percentiles: [0.0043 0.053 0.077 0.088 0.096 0.11 0.13 0.15 0.19 0.27 2.1], mean=0.15, rms=0.22
module=encoder.encoder.layers.8.lstm.grad[0], dim=1, size=5..51, rms percentiles: [0.0074 0.023 0.051 0.061 0.068 0.075 0.086 0.1 0.13 0.19 2.8], mean=0.11, rms=0.22
module=encoder.encoder.layers.9.lstm.grad[0], dim=1, size=5..51, rms percentiles: [0.019 0.044 0.05 0.056 0.061 0.068 0.077 0.089 0.1 0.14 3.1], mean=0.099, rms=0.22
```

**Comment by danpovey** [comment]
For the record: further experiments with various iterations of the gradient-filtering idea seem to make very little difference to the actual results.  Oddly, gradient explosion seems to make very little difference to the convergence, even though it clearly does happen, and we are not even using gradient clipping.  It must be quite rare; perhaps we were just unlucky to see it in the diagnostics that we looked at.

**Pull request merged**
