### PR TITLE
Modified train.py of tedlium3 models

### PR DESCRIPTION
**Pull request by shcxlee**

### CODE REVIEW

**Comment by shcxlee** [comment]
Okay, it seems like it's failing all style checks...

**Comment by csukuangfj** [comment]
> Okay, it seems like it's failing all style checks...

Could you merge the latest master from icefall into your current branch and push it again?

**Comment by shcxlee** [comment]
> Could you merge the latest master from icefall into your current branch and push it again?

I merged them but it still fails...

**Comment by csukuangfj** [comment]
Never mind. It fails only for Python 3.7.


Thanks! Merging.

**Pull request merged**
