### PR TITLE
Replace LilcomChunkyWriter with ChunkedLilcomHdf5Writer.

### PR DESCRIPTION
**Pull request by csukuangfj**
It seems that there are issues with LilcomChunkyWriter in the multi-threaded scenario.

See
- https://github.com/k2-fsa/icefall/discussions/391#discussioncomment-2870627
- https://github.com/k2-fsa/icefall/discussions/391#discussioncomment-2885434
- https://github.com/lhotse-speech/lhotse/issues/607#issue-1157450209
- https://github.com/lhotse-speech/lhotse/issues/607#issuecomment-1148373507

One advantage of using ChunkedLilcomHdf5Writer is that it does not need to compete for locks in
the case of multiple threads.

### CODE REVIEW

**Comment by pzelasko** [comment]
Unfortunately, I wasn’t able to reproduce the issues you had in the other discussion. If you can create a minimal case that helps with repro I could try to fix it in LilcomChunky. HDF5 unfortunately will cause issues to ‚big data’ users…

**Comment by danpovey** [comment]
Definitely having 2 worker threads or more per data-loader process is important.
Unfortunately thread-safety bugs can be hard to reproduce.

**Comment by csukuangfj** [comment]
I am trying to extract a subset of the data, upload it to huggingface and try to reproduce in colab notebook.

**Comment by csukuangfj** [comment]
It is 100% reproducible locally.

**Pull request merged**
