### PR TITLE
First attempt to add WEB client to the streaming emformer.

### PR DESCRIPTION
**Pull request by csukuangfj**
It supports reading a wav file from the client and sends it to the server for recognition at present.

Note: Even though we send all the samples at once, the server supports accepting samples coming in a streaming fashion.

## Example screen recording:

https://user-images.githubusercontent.com/5284924/167114390-de28e2c7-4f97-4641-b5ff-bfe71f0554e8.mov

### CODE REVIEW

**Comment by pkufool** [comment]
I also use websocket, it is in python. I think they are similar, but mine is very simple, I implement it in case we will need a demo for speechhome meeting. @csukuangfj  you can go ahead, I have not done much survey about the server framework.

**Comment by csukuangfj** [comment]
The following is a demo for streaming recognition from real-time recordings.


https://user-images.githubusercontent.com/5284924/167253183-7115a96e-1095-4145-969b-69d72079e043.mov

**Comment by csukuangfj** [comment]
> wow, nice!! Does this actually reflect when it is doing the recognition?

Do you mean the tail padding issue? I think this PR is using a version of beam search before we fix the padding issue.

**Comment by danpovey** [comment]
I meant the video plays audio and shows recognition, I wonder if this is somehow "real" and reflects how fast you could recognize real live audio.

**Comment by pzelasko** [comment]
It looks like it has sth around 200-300ms latency between the time I hear a word and it appears in the recognition, I'd that's easily representative of actual live performance.

**Comment by csukuangfj** [comment]
> I meant the video plays audio and shows recognition, I wonder if this is somehow "real" and reflects how fast you could recognize real live audio.

Yes, I replayed two test waves from the test-clean dataset from my phone.

**Pull request merged**
