### PR TITLE
WIP: Add documentation.

### PR DESCRIPTION
**Pull request by csukuangfj**
A preview is available by visiting the following address:

https://icefall.readthedocs.io/en/latest/

---

Screenshots of the documentation:

Screen Shot 2021-08-23 at 8 25 25 PM
Screen Shot 2021-08-23 at 8 25 44 PM
Screen Shot 2021-08-23 at 8 31 55 PM

### CODE REVIEW

**Comment by danpovey** [comment]
That looks great!
The colab notebook is a nice touch.

**Comment by csukuangfj** [comment]
> That looks great!
> The colab notebook is a nice touch.

Shall we choose a dedicated place to save such notebooks, say, a GitHub repo?

**Comment by danpovey** [comment]
Regarding the colab notebooks: I'm OK with that as long as it doesn't make it harder to get things done... but maybe not a short-term/urgent priority?

**Comment by csukuangfj** [comment]
> Regarding the colab notebooks: I'm OK with that as long as it doesn't make it harder to get things done... but maybe not a short-term/urgent priority?

Yeah, it's not urgent. If later we have lots of notebooks, we can start to find a place to put them.

**Comment by csukuangfj** [comment]
Merging so that @pkufool can also work on this.

**Pull request merged**
