### PR TITLE
Add docker image for icefall

### PR DESCRIPTION
**Pull request by csukuangfj**
Usage
```bash
docker run --gpus all --rm -it  k2fsa/icefall:torch1.13.0-cuda11.6 /bin/bash
```

Would be great if someone can test it.

### CODE REVIEW

**Comment by teowenshen** [comment]
Somehow the CUDA version inside the container shows error for me.

I am not sure about the difference between `--runtime=nvidia` and `--gpus=all`, but I tried all 3 combinations.

```bash
teo@s64:~$ nvidia-smi
Thu Jul 27 20:43:08 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.47.03    Driver Version: 510.47.03    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:18:00.0 Off |                  N/A |
|  0%   49C    P8    30W / 350W |      5MiB / 24576MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1758      G   /usr/lib/xorg/Xorg                  4MiB |
+-----------------------------------------------------------------------------+
teo@s64:~$ docker run --rm -it  k2fsa/icefall:torch1.13.0-cuda11.6 /bin/bash
root@ae8acaf91ea0:/workspace/icefall# nvidia-smi
bash: nvidia-smi: command not found
root@ae8acaf91ea0:/workspace/icefall# exit
teo@s64:~$ docker run --rm -it --gpus=all k2fsa/icefall:torch1.13.0-cuda11.6 /bin/bash
root@c5f8c3bc2883:/workspace/icefall# nvidia-smi
Thu Jul 27 11:43:39 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.47.03    Driver Version: 510.47.03    CUDA Version: ERR!     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:18:00.0 Off |                  N/A |
|  0%   50C    P8    42W / 350W |      5MiB / 24576MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1758      G                                       4MiB |
+-----------------------------------------------------------------------------+
root@c5f8c3bc2883:/workspace/icefall# exit
teo@s64:~$ docker run --rm -it --runtime=nvidia k2fsa/icefall:torch1.13.0-cuda11.6 /bin/bash
root@1cb84e2f0eaa:/workspace/icefall# nvidia-smi
Thu Jul 27 11:43:51 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.47.03    Driver Version: 510.47.03    CUDA Version: ERR!     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:18:00.0 Off |                  N/A |
|  0%   49C    P8    30W / 350W |      5MiB / 24576MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1758      G                                       4MiB |
+-----------------------------------------------------------------------------+
root@1cb84e2f0eaa:/workspace/icefall# exit
teo@s64:~$ docker run --rm -it --runtime=nvidia --gpus=all k2fsa/icefall:torch1.13.0-cuda11.6 /bin/bash
root@bcc29879157e:/workspace/icefall# nvidia-smi
Thu Jul 27 11:44:02 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.47.03    Driver Version: 510.47.03    CUDA Version: ERR!     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:18:00.0 Off |                  N/A |
|  0%   49C    P8    32W / 350W |      5MiB / 24576MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1758      G                                       4MiB |
+-----------------------------------------------------------------------------+
root@bcc29879157e:/workspace/icefall# exit
```

With this error, I tried running a `decode.py`. This warning came up and GPU was not utilized.


> /opt/conda/lib/python3.9/site-packages/torch/cuda/__init__.py:88: UserWarning: CUDA initialization: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 34: CUDA driver is a stub library (Triggered internally at /opt/conda/conda-bld/pytorch_1666643016022/work/c10/cuda/CUDAFunctions.cpp:109.)

**Comment by danpovey** [comment]
maybe need to run with nvidia-docker instead of docker if planning to use the GPU?

**Comment by teowenshen** [comment]
I tried with `nvidia-docker`, but it's the same. 
In the `docker image ls` below, `icefall` is the image that I compiled locally using the existing docker build file while `k2fsa/icefall` is the new downloaded image.
My local image could detect the GPU, while the downloaded image could not. 

There is a size difference between my image and the new image. It is partly because I installed sherpa into my image, but I am not sure if the entire 4.2GB came from sherpa.

```bash
teo@s64:~$ nvidia-docker run --rm -it  k2fsa/icefall:torch1.13.0-cuda11.6 /bin/bash
root@84b25aedbe2d:/workspace/icefall# nvidia-smi
Thu Jul 27 13:17:12 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.47.03    Driver Version: 510.47.03    CUDA Version: ERR!     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:18:00.0 Off |                  N/A |
|  0%   51C    P8    31W / 350W |      5MiB / 24576MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1758      G                                       4MiB |
+-----------------------------------------------------------------------------+
root@84b25aedbe2d:/workspace/icefall# exit
teo@s64:~$ docker image ls
REPOSITORY                    TAG                               IMAGE ID       CREATED         SIZE
k2fsa/icefall                 torch1.13.0-cuda11.6              3b0e967ec78a   2 hours ago     12.1GB
icefall                       latest                            3be62493eab5   5 days ago      16.3GB
...
[omitted]
...
teo@s64:~$ nvidia-docker run -it --rm icefall bash
root@2e812284fec7:/workspace/icefall# nvidia-smi
Thu Jul 27 13:17:37 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.47.03    Driver Version: 510.47.03    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:18:00.0 Off |                  N/A |
|  0%   50C    P8    30W / 350W |      5MiB / 24576MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1758      G                                       4MiB |
+-----------------------------------------------------------------------------+
```

**Comment by csukuangfj** [comment]
@teowenshen 

Thanks for testing it.

The icefall docker image is based on
https://github.com/k2-fsa/icefall/blob/e8270e6d7441321876eae3ccdf5e2e3b3c66ae9d/docker/torch1.13.0-cuda11.6-cudnn8.dockerfile#L1

Could you test `pytorch/pytorch:1.13.0-cuda11.6-cudnn8-runtime` and see if it works with `nvidia-smi`?

If not, could you try
```bash
pytorch/pytorch:1.13.0-cuda11.6-cudnn8-devel 
```

**Comment by csukuangfj** [comment]
Could you remove the following line from the icefall docker image
https://github.com/csukuangfj/icefall/blob/130ac92d05e11a502dd1d7dca9ea7c76e5a855d8/docker/torch1.13.0-cuda11.6-cudnn8.dockerfile#L47
and retry?
```
RUN cd /opt/conda/lib/stubs && ln -s libcuda.so libcuda.so.1
```

That line is added to fix a GitHub action test error, saying that `libcuda.so.1` cannot be found when running `python3 -m k2.version`.

I think `libcuda.so.1` is provided by the host.

---

Note: You don't need to re-build the icefall docker image. Just start the container and delete that file from the container and re-run `nvidia-smi`.

**Comment by teowenshen** [comment]
You are right! I deleted `/opt/conda/lib/stubs/libcuda.so.1` and `nvidia-smi` worked normally. Below is the output from python -m k2.version.

```bash
root@d8cf0e860304:~# python -m k2.version
Collecting environment information...

k2 version: 1.24.3
Build type: Release
Git SHA1: 4c05309499a08454997adf500b56dcc629e35ae5
Git date: Tue Jul 25 16:23:36 2023
Cuda used to build k2: 11.6
cuDNN used to build k2: 8.3.2
Python version used to build k2: 3.9
OS used to build k2: CentOS Linux release 7.9.2009 (Core)
CMake version: 3.27.0
GCC version: 9.3.1
CMAKE_CUDA_FLAGS:  -Wno-deprecated-gpu-targets   -lineinfo --expt-extended-lambda -use_fast_math -Xptxas=-w  --expt-extended-lambda -gencode arch=compute_35,code=sm_35  -lineinfo --expt-extended-lambda -use_fast_math -Xptxas=-w  --expt-extended-lambda -gencode arch=compute_50,code=sm_50  -lineinfo --expt-extended-lambda -use_fast_math -Xptxas=-w  --expt-extended-lambda -gencode arch=compute_60,code=sm_60  -lineinfo --expt-extended-lambda -use_fast_math -Xptxas=-w  --expt-extended-lambda -gencode arch=compute_61,code=sm_61  -lineinfo --expt-extended-lambda -use_fast_math -Xptxas=-w  --expt-extended-lambda -gencode arch=compute_70,code=sm_70  -lineinfo --expt-extended-lambda -use_fast_math -Xptxas=-w  --expt-extended-lambda -gencode arch=compute_75,code=sm_75  -lineinfo --expt-extended-lambda -use_fast_math -Xptxas=-w  --expt-extended-lambda -gencode arch=compute_80,code=sm_80  -lineinfo --expt-extended-lambda -use_fast_math -Xptxas=-w  --expt-extended-lambda -gencode arch=compute_86,code=sm_86 -DONNX_NAMESPACE=onnx_c2 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_50,code=sm_50 -gencode arch=compute_52,code=sm_52 -gencode arch=compute_60,code=sm_60 -gencode arch=compute_61,code=sm_61 -gencode arch=compute_70,code=sm_70 -gencode arch=compute_75,code=sm_75 -gencode arch=compute_80,code=sm_80 -gencode arch=compute_86,code=sm_86 -gencode arch=compute_86,code=compute_86 -Xcudafe --diag_suppress=cc_clobber_ignored,--diag_suppress=integer_sign_change,--diag_suppress=useless_using_declaration,--diag_suppress=set_but_not_used,--diag_suppress=field_without_dll_interface,--diag_suppress=base_class_has_different_dll_interface,--diag_suppress=dll_interface_conflict_none_assumed,--diag_suppress=dll_interface_conflict_dllexport_assumed,--diag_suppress=implicit_return_from_non_void_function,--diag_suppress=unsigned_compare_with_zero,--diag_suppress=declared_but_not_referenced,--diag_suppress=bad_friend_decl --expt-relaxed-constexpr --expt-extended-lambda -D_GLIBCXX_USE_CXX11_ABI=0 --compiler-options -Wall  --compiler-options -Wno-strict-overflow  --compiler-options -Wno-unknown-pragmas 
CMAKE_CXX_FLAGS:  -D_GLIBCXX_USE_CXX11_ABI=0 -Wno-unused-variable  -Wno-strict-overflow 
PyTorch version used to build k2: 1.13.0+cu116
PyTorch is using Cuda: 11.6
NVTX enabled: True
With CUDA: True
Disable debug: True
Sync kernels : False
Disable checks: False
Max cpu memory allocate: 214748364800 bytes (or 200.0 GB)
k2 abort: False
__file__: /opt/conda/lib/python3.9/site-packages/k2/version/version.py
_k2.__file__: /opt/conda/lib/python3.9/site-packages/_k2.cpython-39-x86_64-linux-gnu.so
```

I also ran a `decode.py` and can confirm that GPU is being utilized.

**Comment by csukuangfj** [comment]
@teowenshen 

Thank you for testing it. 

I have fixed the dockerfile and everything should work as expected.

**Comment by teowenshen** [comment]
@csukuangfj 

Sorry to reuse this PR, but just a quick note that there is a typo in the link.

image

**Comment by csukuangfj** [comment]
> @csukuangfj
> 
> Sorry to reuse this PR, but just a quick note that there is a typo in the link.
> 
> image

Thanks! Just fixed it.

**Pull request merged**
