### PR TITLE
fix compiling HLG

### PR DESCRIPTION
**Pull request by csukuangfj**
Someone is trying the TIMIT recipe and gets the following error
image

The error is introduced by https://github.com/k2-fsa/k2/pull/1140
This PR fixes the error.

### CODE REVIEW

**Comment by rouseabout** [comment]
@csukuangfj I still encounter the problem on yesno :( Any suggestions?

```
(testing) user@computer:~/workspace/icefall/egs/yesno/ASR$ ./prepare.sh 
2023-05-08 08:27:41 (prepare.sh:27:main) dl_dir: /home/user/workspace/icefall/egs/yesno/ASR/download
2023-05-08 08:27:41 (prepare.sh:30:main) Stage 0: Download data
2023-05-08 08:27:41 (prepare.sh:39:main) Stage 1: Prepare yesno manifest
2023-05-08 08:27:44 (prepare.sh:45:main) Stage 2: Compute fbank for yesno
2023-05-08 08:27:46,058 INFO [compute_fbank_yesno.py:63] train already exists - skipping.
2023-05-08 08:27:46,058 INFO [compute_fbank_yesno.py:63] test already exists - skipping.
2023-05-08 08:27:46 (prepare.sh:51:main) Stage 3: Prepare lang
2023-05-08 08:27:49 (prepare.sh:66:main) Stage 4: Prepare G
2023-05-08 08:27:49 (prepare.sh:92:main) Stage 5: Compile HLG
2023-05-08 08:27:51,750 INFO [compile_hlg.py:124] Processing data/lang_phone
2023-05-08 08:27:51,750 INFO [lexicon.py:168] Loading pre-compiled data/lang_phone/Linv.pt
2023-05-08 08:27:51,751 INFO [compile_hlg.py:48] Building ctc_topo. max_token_id: 3
2023-05-08 08:27:51,752 INFO [compile_hlg.py:52] Loading G.fst.txt
2023-05-08 08:27:51,752 INFO [compile_hlg.py:62] Intersecting L and G
2023-05-08 08:27:51,754 INFO [compile_hlg.py:64] LG shape: (4, None)
2023-05-08 08:27:51,754 INFO [compile_hlg.py:66] Connecting LG
2023-05-08 08:27:51,754 INFO [compile_hlg.py:68] LG shape after k2.connect: (4, None)
2023-05-08 08:27:51,754 INFO [compile_hlg.py:70] <class 'torch.Tensor'>
2023-05-08 08:27:51,754 INFO [compile_hlg.py:71] Determinizing LG
2023-05-08 08:27:51,755 INFO [compile_hlg.py:74] <class '_k2.ragged.RaggedTensor'>
2023-05-08 08:27:51,755 INFO [compile_hlg.py:76] Connecting LG after k2.determinize
2023-05-08 08:27:51,755 INFO [compile_hlg.py:79] Removing disambiguation symbols on LG
2023-05-08 08:27:51,756 INFO [compile_hlg.py:91] LG shape after k2.remove_epsilon: (6, None)
Traceback (most recent call last):
  File "/home/user/workspace/icefall/egs/yesno/ASR/./local/compile_hlg.py", line 136, in <module>
    main()
  File "/home/user/workspace/icefall/egs/yesno/ASR/./local/compile_hlg.py", line 126, in main
    HLG = compile_HLG(lang_dir)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/workspace/icefall/egs/yesno/ASR/./local/compile_hlg.py", line 93, in compile_HLG
    LG = k2.connect(LG)
         ^^^^^^^^^^^^^^
  File "/home/user/workspace/testing/lib/python3.11/site-packages/k2-1.24.1.dev20230507+cpu.torch2.0.0-py3.11-linux-x86_64.egg/k2/fsa_algo.py", line 522, in connect
    if fsa.properties & fsa_properties.ACCESSIBLE != 0 and \
       ^^^^^^^^^^^^^^
  File "/home/user/workspace/testing/lib/python3.11/site-packages/k2-1.24.1.dev20230507+cpu.torch2.0.0-py3.11-linux-x86_64.egg/k2/fsa.py", line 446, in properties
    raise RuntimeError(
RuntimeError: The fsa attribute (labels) has been inappropriately modified like:
    fsa.labels[xxx] = yyy
The correct way should be like:
    labels = fsa.labels
    labels[xxx] = yyy
    fsa.labels = labels
```

**Comment by csukuangfj** [comment]
> @csukuangfj I still encounter the problem on yesno :( Any suggestions?
> 
> 
> 
> ```
> 
> (testing) user@computer:~/workspace/icefall/egs/yesno/ASR$ ./prepare.sh 
> 
> 2023-05-08 08:27:41 (prepare.sh:27:main) dl_dir: /home/user/workspace/icefall/egs/yesno/ASR/download
> 
> 2023-05-08 08:27:41 (prepare.sh:30:main) Stage 0: Download data
> 
> 2023-05-08 08:27:41 (prepare.sh:39:main) Stage 1: Prepare yesno manifest
> 
> 2023-05-08 08:27:44 (prepare.sh:45:main) Stage 2: Compute fbank for yesno
> 
> 2023-05-08 08:27:46,058 INFO [compute_fbank_yesno.py:63] train already exists - skipping.
> 
> 2023-05-08 08:27:46,058 INFO [compute_fbank_yesno.py:63] test already exists - skipping.
> 
> 2023-05-08 08:27:46 (prepare.sh:51:main) Stage 3: Prepare lang
> 
> 2023-05-08 08:27:49 (prepare.sh:66:main) Stage 4: Prepare G
> 
> 2023-05-08 08:27:49 (prepare.sh:92:main) Stage 5: Compile HLG
> 
> 2023-05-08 08:27:51,750 INFO [compile_hlg.py:124] Processing data/lang_phone
> 
> 2023-05-08 08:27:51,750 INFO [lexicon.py:168] Loading pre-compiled data/lang_phone/Linv.pt
> 
> 2023-05-08 08:27:51,751 INFO [compile_hlg.py:48] Building ctc_topo. max_token_id: 3
> 
> 2023-05-08 08:27:51,752 INFO [compile_hlg.py:52] Loading G.fst.txt
> 
> 2023-05-08 08:27:51,752 INFO [compile_hlg.py:62] Intersecting L and G
> 
> 2023-05-08 08:27:51,754 INFO [compile_hlg.py:64] LG shape: (4, None)
> 
> 2023-05-08 08:27:51,754 INFO [compile_hlg.py:66] Connecting LG
> 
> 2023-05-08 08:27:51,754 INFO [compile_hlg.py:68] LG shape after k2.connect: (4, None)
> 
> 2023-05-08 08:27:51,754 INFO [compile_hlg.py:70] <class 'torch.Tensor'>
> 
> 2023-05-08 08:27:51,754 INFO [compile_hlg.py:71] Determinizing LG
> 
> 2023-05-08 08:27:51,755 INFO [compile_hlg.py:74] <class '_k2.ragged.RaggedTensor'>
> 
> 2023-05-08 08:27:51,755 INFO [compile_hlg.py:76] Connecting LG after k2.determinize
> 
> 2023-05-08 08:27:51,755 INFO [compile_hlg.py:79] Removing disambiguation symbols on LG
> 
> 2023-05-08 08:27:51,756 INFO [compile_hlg.py:91] LG shape after k2.remove_epsilon: (6, None)
> 
> Traceback (most recent call last):
> 
>   File "/home/user/workspace/icefall/egs/yesno/ASR/./local/compile_hlg.py", line 136, in <module>
> 
>     main()
> 
>   File "/home/user/workspace/icefall/egs/yesno/ASR/./local/compile_hlg.py", line 126, in main
> 
>     HLG = compile_HLG(lang_dir)
> 
>           ^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/home/user/workspace/icefall/egs/yesno/ASR/./local/compile_hlg.py", line 93, in compile_HLG
> 
>     LG = k2.connect(LG)
> 
>          ^^^^^^^^^^^^^^
> 
>   File "/home/user/workspace/testing/lib/python3.11/site-packages/k2-1.24.1.dev20230507+cpu.torch2.0.0-py3.11-linux-x86_64.egg/k2/fsa_algo.py", line 522, in connect
> 
>     if fsa.properties & fsa_properties.ACCESSIBLE != 0 and \
> 
>        ^^^^^^^^^^^^^^
> 
>   File "/home/user/workspace/testing/lib/python3.11/site-packages/k2-1.24.1.dev20230507+cpu.torch2.0.0-py3.11-linux-x86_64.egg/k2/fsa.py", line 446, in properties
> 
>     raise RuntimeError(
> 
> RuntimeError: The fsa attribute (labels) has been inappropriately modified like:
> 
>     fsa.labels[xxx] = yyy
> 
> The correct way should be like:
> 
>     labels = fsa.labels
> 
>     labels[xxx] = yyy
> 
>     fsa.labels = labels
> 
> ```

Are you using the latest master of k2?

You have to install k2 from the latest master.

Please show the output of 

python3 -m k2.version

**Comment by rouseabout** [comment]
Yes using latest master (8740cc821c10a48723cb4d0cbef75b18c68f4878):

```
(tesing) user@computer:~/workspace/icefall/egs/yesno/ASR$ python3 -m k2.version
Collecting environment information...

k2 version: 1.24.1
Build type: Release
Git SHA1: 8740cc821c10a48723cb4d0cbef75b18c68f4878
Git date: Sun May 7 17:52:20 2023
Cuda used to build k2: 
cuDNN used to build k2: 
Python version used to build k2: 3.11
OS used to build k2: Debian GNU/Linux 12 (bookworm)
CMake version: 3.25.1
GCC version: 12.2.0
CMAKE_CUDA_FLAGS: 
CMAKE_CXX_FLAGS:  -D_GLIBCXX_USE_CXX11_ABI=0 -Wno-unused-variable  -Wno-strict-overflow 
PyTorch version used to build k2: 2.0.0+cpu
PyTorch is using Cuda: 
NVTX enabled: False
With CUDA: False
Disable debug: True
Sync kernels : False
Disable checks: False
Max cpu memory allocate: 214748364800 bytes (or 200.0 GB)
k2 abort: False
__file__: /home/user/workspace/testing/lib/python3.11/site-packages/k2-1.24.1.dev20230507+cpu.torch2.0.0-py3.11-linux-x86_64.egg/k2/version/version.py
_k2.__file__: /home/user/workspace/testing/lib/python3.11/site-packages/k2-1.24.1.dev20230507+cpu.torch2.0.0-py3.11-linux-x86_64.egg/_k2.cpython-311-x86_64-linux-gnu.so

```

**Comment by csukuangfj** [comment]
> Yes using latest master (8740cc821c10a48723cb4d0cbef75b18c68f4878):
> 
> ```
> (tesing) user@computer:~/workspace/icefall/egs/yesno/ASR$ python3 -m k2.version
> Collecting environment information...
> 
> k2 version: 1.24.1
> Build type: Release
> Git SHA1: 8740cc821c10a48723cb4d0cbef75b18c68f4878
> Git date: Sun May 7 17:52:20 2023
> Cuda used to build k2: 
> cuDNN used to build k2: 
> Python version used to build k2: 3.11
> OS used to build k2: Debian GNU/Linux 12 (bookworm)
> CMake version: 3.25.1
> GCC version: 12.2.0
> CMAKE_CUDA_FLAGS: 
> CMAKE_CXX_FLAGS:  -D_GLIBCXX_USE_CXX11_ABI=0 -Wno-unused-variable  -Wno-strict-overflow 
> PyTorch version used to build k2: 2.0.0+cpu
> PyTorch is using Cuda: 
> NVTX enabled: False
> With CUDA: False
> Disable debug: True
> Sync kernels : False
> Disable checks: False
> Max cpu memory allocate: 214748364800 bytes (or 200.0 GB)
> k2 abort: False
> __file__: /home/user/workspace/testing/lib/python3.11/site-packages/k2-1.24.1.dev20230507+cpu.torch2.0.0-py3.11-linux-x86_64.egg/k2/version/version.py
> _k2.__file__: /home/user/workspace/testing/lib/python3.11/site-packages/k2-1.24.1.dev20230507+cpu.torch2.0.0-py3.11-linux-x86_64.egg/_k2.cpython-311-x86_64-linux-gnu.so
> ```

Are you using the latest icefall? You can use 
```
git log
```
to view the commit to check that.

**Comment by danpovey** [comment]
latest master is 1.24.2 no?  Or is that a more recent PR?

**Comment by csukuangfj** [comment]
I just released 1.24.2 this morning, which only changed CMakeLists.txt.
(The latest was 8740cc821c10a48723cb4d0cbef75b18c68f4878 after merging https://github.com/k2-fsa/k2/pull/1186)

**Comment by csukuangfj** [comment]
@rouseabout 
Please use changes from https://github.com/k2-fsa/k2/pull/1188
It should fix your issue.

**Comment by rouseabout** [comment]
成功！

**Pull request merged**
