### PR TITLE
Export streaming zipformer to ncnn

### PR DESCRIPTION
**Pull request by csukuangfj**
This pull-request supports exporting [`streaming Zipformer`](https://github.com/k2-fsa/icefall/tree/master/egs/librispeech/ASR/pruned_transducer_stateless7_streaming) to [ncnn](https://github.com/tencent/ncnn/) so that we can use it in
[sherpa-ncnn](https://github.com/csukuangfj/sherpa-ncnn)

Two exported models can be found at
- Bilingual (Chinese + English): https://huggingface.co/csukuangfj/sherpa-ncnn-streaming-zipformer-bilingual-zh-en-2023-02-13
- English: https://huggingface.co/csukuangfj/sherpa-ncnn-streaming-zipformer-en-2023-02-13

## TODOs
- [ ] Add documentation for the export
- [ ] Export the Japanese pre-trained model from  #892 
- [ ] Android demo with [sherpa-ncnn](https://github.com/csukuangfj/sherpa-ncnn)
- [ ] iOS demo with [sherpa-ncnn](https://github.com/csukuangfj/sherpa-ncnn)
- [ ] Rapsberry Pi demo with [sherpa-ncnn](https://github.com/csukuangfj/sherpa-ncnn)
- [ ] [m3axpi](https://wiki.sipeed.com/hardware/en/maixIII/ax-pi/axpi.html) demo with [sherpa-ncnn](https://github.com/csukuangfj/sherpa-ncnn)
- [ ] Python demo with with [sherpa-ncnn](https://github.com/csukuangfj/sherpa-ncnn)

### CODE REVIEW

**Comment by kobenaxie** [comment]
hi, @csukuangfj when using [ncnn/pnnx:30f3f8baa549bb15f8e0a39cd8b12c3a5405a44c ](https://github.com/csukuangfj/sherpa-ncnn)to convert model, but get some `pnnx.Expression          pnnx_expr_3459           1 1 143 145` in model.param, which leads to segmentation fault with error `layer pnnx.Expression not exists or registered`, have you encounter this ?

**Comment by csukuangfj** [comment]
> hi, @csukuangfj when using [ncnn/pnnx:30f3f8baa549bb15f8e0a39cd8b12c3a5405a44c ](https://github.com/csukuangfj/sherpa-ncnn)to convert model, but get some `pnnx.Expression          pnnx_expr_3459           1 1 143 145` in model.param, which leads to segmentation fault with error `layer pnnx.Expression not exists or registered`, have you encounter this ?

Are you using the latest icefall and csukuangfj/ncnn ?

**Comment by csukuangfj** [comment]
What does `ncnn/pnnx:30f3f8baa549bb15f8e0a39cd8b12c3a5405a44c ` point to?

**Comment by csukuangfj** [comment]
Do you mean

```
https://github.com/csukuangfj/ncnn/commit/30f3f8baa549bb15f8e0a39cd8b12c3a5405a44c
```
?

Could you show the exact command you are using? 

Please also make sure you are using the master of icefall.

**Comment by kobenaxie** [comment]
> Do you mean
> 
> ```
> https://github.com/csukuangfj/ncnn/commit/30f3f8baa549bb15f8e0a39cd8b12c3a5405a44c
> ```
> 
> ?
> 
> Could you show the exact command you are using?
> 
> Please also make sure you are using the master of icefall.

yes, it is the commit ID of ncnn(from your repository）

**Comment by csukuangfj** [comment]
Please remove the build directory of pnnx and ncnn, and then re-build ncnn and pnnx before you re-try.

**Comment by kobenaxie** [comment]
> Please remove the build directory of pnnx and ncnn, and then re-build ncnn and pnnx before you re-try.

Sorry, it is my mistake, forgetting pass `is_pnnx` to `Zipformer()`.

**Comment by csukuangfj** [comment]
> > Please remove the build directory of pnnx and ncnn, and then re-build ncnn and pnnx before you re-try.
> 
> Sorry, it is my mistake, forgetting pass `is_pnnx` to `Zipformer()`.

Are you using your own code instead of using the master branch of icefall?

**Comment by csukuangfj** [comment]
Please follow
https://huggingface.co/csukuangfj/sherpa-ncnn-streaming-zipformer-bilingual-zh-en-2023-02-13/blob/main/export-for-ncnn-bilingual.sh#L39
to change `encoder_xxx.ncnn.param` after converting to pnnx. I will update the doc later.

Screenshot 2023-02-15 at 11 58 26

**Comment by kobenaxie** [comment]
> > > Please remove the build directory of pnnx and ncnn, and then re-build ncnn and pnnx before you re-try.
> > 
> > 
> > Sorry, it is my mistake, forgetting pass `is_pnnx` to `Zipformer()`.
> 
> Are you using your own code instead of using the master branch of icefall?

Yes，but only remove the last downsampling layer.

**Comment by kobenaxie** [comment]
> Please follow https://huggingface.co/csukuangfj/sherpa-ncnn-streaming-zipformer-bilingual-zh-en-2023-02-13/blob/main/export-for-ncnn-bilingual.sh#L39 to change `encoder_xxx.ncnn.param` after converting to pnnx. I will update the doc later.
> 
> Screenshot 2023-02-15 at 11 58 26

Thanks！

**Pull request merged**
