### PR TITLE
Update GigaSpeech reults

### PR DESCRIPTION
**Pull request by wgb14**
This is based on fixes in #361

### CODE REVIEW

**Comment by wgb14** [comment]
Post decoding logs here
```log
2022-05-14 03:14:32,054 INFO [decode.py:489] Decoding started
2022-05-14 03:14:32,055 INFO [decode.py:495] Device: cuda:0
2022-05-14 03:14:32,057 INFO [decode.py:505] {'best_train_loss': inf, 'best_valid_loss': inf, 'best_train_epoch': -1, 'best_valid_epoch': -1, 'batch_idx_train': 0, 'log_interval': 500, 'reset_interval': 2000, 'valid_interval': 20000, 'feature_dim': 80, 'subsampling_factor': 4, 'encoder_dim': 512, 'nhead': 8, 'dim_feedforward': 2048, 'num_encoder_layers': 12, 'decoder_dim': 512, 'joiner_dim': 512, 'model_warm_step': 20000, 'env_info': {'k2-version': '1.14', 'k2-build-type': 'Release', 'k2-with-cuda': True, 'k2-git-sha1': '1b29f0a946f50186aaa82df46a59f492ade9692b', 'k2-git-date': 'Wed Apr 13 08:46:49 2022', 'lhotse-version': '1.1.0', 'torch-version': '1.10.0', 'torch-cuda-available': True, 'torch-cuda-version': '11.1', 'python-version': '3.7', 'icefall-git-branch': 'master', 'icefall-git-sha1': 'e30e042-dirty', 'icefall-git-date': 'Fri May 13 13:03:16 2022', 'icefall-path': '/userhome/user/guanbo/icefall_master', 'k2-path': '/opt/conda/lib/python3.7/site-packages/k2-1.14.dev20220513+cuda11.1.torch1.10.0-py3.7-linux-x86_64.egg/k2/__init__.py', 'lhotse-path': '/userhome/user/guanbo/lhotse/lhotse/__init__.py', 'hostname': 'b08cab400d29a011ec0b6ec0bb60bea6856f-chenx8564-0', 'IP address': '10.44.46.67'}, 'epoch': 29, 'iter': 0, 'avg': 8, 'exp_dir': PosixPath('pruned_transducer_stateless2/exp_500_8'), 'bpe_model': 'data/lang_bpe_500/bpe.model', 'decoding_method': 'modified_beam_search', 'beam_size': 4, 'beam': 4, 'max_contexts': 4, 'max_states': 8, 'context_size': 2, 'max_sym_per_frame': 1, 'manifest_dir': PosixPath('data/fbank'), 'max_duration': 600, 'bucketing_sampler': True, 'num_buckets': 30, 'concatenate_cuts': False, 'duration_factor': 1.0, 'gap': 1.0, 'on_the_fly_feats': False, 'shuffle': True, 'return_cuts': True, 'num_workers': 4, 'enable_spec_aug': True, 'spec_aug_time_warp_factor': 80, 'enable_musan': True, 'subset': 'XL', 'small_dev': False, 'res_dir': PosixPath('pruned_transducer_stateless2/exp_500_8/modified_beam_search'), 'suffix': 'epoch-29-avg-8-beam-4', 'blank_id': 0, 'unk_id': 2, 'vocab_size': 500}
2022-05-14 03:14:32,058 INFO [decode.py:507] About to create model
2022-05-14 03:14:32,459 INFO [decode.py:535] averaging ['pruned_transducer_stateless2/exp_500_8/epoch-22.pt', 'pruned_transducer_stateless2/exp_500_8/epoch-23.pt', 'pruned_transducer_stateless2/exp_500_8/epoch-24.pt', 'pruned_transducer_stateless2/exp_500_8/epoch-25.pt', 'pruned_transducer_stateless2/exp_500_8/epoch-26.pt', 'pruned_transducer_stateless2/exp_500_8/epoch-27.pt', 'pruned_transducer_stateless2/exp_500_8/epoch-28.pt', 'pruned_transducer_stateless2/exp_500_8/epoch-29.pt']
2022-05-14 03:14:42,765 INFO [decode.py:549] Number of model parameters: 78648040
2022-05-14 03:14:42,766 INFO [asr_datamodule.py:406] About to get dev cuts
2022-05-14 03:15:41,904 INFO [decode.py:401] batch 0/?, cuts processed until now is 99
2022-05-14 03:18:39,814 INFO [decode.py:401] batch 20/?, cuts processed until now is 1626
2022-05-14 03:22:46,008 INFO [decode.py:401] batch 40/?, cuts processed until now is 3172
2022-05-14 03:28:43,825 INFO [decode.py:401] batch 60/?, cuts processed until now is 4929
2022-05-14 03:30:10,564 INFO [decode.py:418] The transcripts are stored in pruned_transducer_stateless2/exp_500_8/modified_beam_search/recogs-dev-beam_size_4-epoch-29-avg-8-beam-4.txt
2022-05-14 03:30:10,711 INFO [utils.py:406] [dev-beam_size_4] %WER 10.51% [13431 / 127790, 3386 ins, 2878 del, 7167 sub ]
2022-05-14 03:30:11,037 INFO [decode.py:431] Wrote detailed error stats to pruned_transducer_stateless2/exp_500_8/modified_beam_search/errs-dev-beam_size_4-epoch-29-avg-8-beam-4.txt
2022-05-14 03:30:11,040 INFO [decode.py:452] 
For dev, WER of different settings are:
beam_size_4	10.51	best for dev

2022-05-14 03:30:11,047 INFO [decode.py:577] Done!
```
```log
2022-05-14 02:21:55,157 INFO [decode_test.py:489] Decoding started
2022-05-14 02:21:55,158 INFO [decode_test.py:495] Device: cuda:0
2022-05-14 02:21:55,162 INFO [decode_test.py:505] {'best_train_loss': inf, 'best_valid_loss': inf, 'best_train_epoch': -1, 'best_valid_epoch': -1, 'batch_idx_train': 0, 'log_interval': 500, 'reset_interval': 2000, 'valid_interval': 20000, 'feature_dim': 80, 'subsampling_factor': 4, 'encoder_dim': 512, 'nhead': 8, 'dim_feedforward': 2048, 'num_encoder_layers': 12, 'decoder_dim': 512, 'joiner_dim': 512, 'model_warm_step': 20000, 'env_info': {'k2-version': '1.14', 'k2-build-type': 'Release', 'k2-with-cuda': True, 'k2-git-sha1': '1b29f0a946f50186aaa82df46a59f492ade9692b', 'k2-git-date': 'Wed Apr 13 08:46:49 2022', 'lhotse-version': '1.1.0', 'torch-version': '1.10.0', 'torch-cuda-available': True, 'torch-cuda-version': '11.1', 'python-version': '3.7', 'icefall-git-branch': 'master', 'icefall-git-sha1': 'e30e042-dirty', 'icefall-git-date': 'Fri May 13 13:03:16 2022', 'icefall-path': '/userhome/user/guanbo/icefall_master', 'k2-path': '/opt/conda/lib/python3.7/site-packages/k2-1.14.dev20220513+cuda11.1.torch1.10.0-py3.7-linux-x86_64.egg/k2/__init__.py', 'lhotse-path': '/userhome/user/guanbo/lhotse/lhotse/__init__.py', 'hostname': 'fef68cd00d298011ec0b6ec0bb60bea6856f-chenx8564-0', 'IP address': '10.206.33.68'}, 'epoch': 29, 'iter': 0, 'avg': 9, 'exp_dir': PosixPath('pruned_transducer_stateless2/exp_500_8'), 'bpe_model': 'data/lang_bpe_500/bpe.model', 'decoding_method': 'modified_beam_search', 'beam_size': 4, 'beam': 4, 'max_contexts': 4, 'max_states': 8, 'context_size': 2, 'max_sym_per_frame': 1, 'manifest_dir': PosixPath('data/fbank'), 'max_duration': 600, 'bucketing_sampler': True, 'num_buckets': 30, 'concatenate_cuts': False, 'duration_factor': 1.0, 'gap': 1.0, 'on_the_fly_feats': False, 'shuffle': True, 'return_cuts': True, 'num_workers': 4, 'enable_spec_aug': True, 'spec_aug_time_warp_factor': 80, 'enable_musan': True, 'subset': 'XL', 'small_dev': False, 'res_dir': PosixPath('pruned_transducer_stateless2/exp_500_8/modified_beam_search'), 'suffix': 'epoch-29-avg-9-beam-4', 'blank_id': 0, 'unk_id': 2, 'vocab_size': 500}
2022-05-14 02:21:55,163 INFO [decode_test.py:507] About to create model
2022-05-14 02:21:55,592 INFO [decode_test.py:535] averaging ['pruned_transducer_stateless2/exp_500_8/epoch-21.pt', 'pruned_transducer_stateless2/exp_500_8/epoch-22.pt', 'pruned_transducer_stateless2/exp_500_8/epoch-23.pt', 'pruned_transducer_stateless2/exp_500_8/epoch-24.pt', 'pruned_transducer_stateless2/exp_500_8/epoch-25.pt', 'pruned_transducer_stateless2/exp_500_8/epoch-26.pt', 'pruned_transducer_stateless2/exp_500_8/epoch-27.pt', 'pruned_transducer_stateless2/exp_500_8/epoch-28.pt', 'pruned_transducer_stateless2/exp_500_8/epoch-29.pt']
2022-05-14 02:22:07,294 INFO [decode_test.py:549] Number of model parameters: 78648040
2022-05-14 02:22:07,295 INFO [asr_datamodule.py:415] About to get test cuts
2022-05-14 02:22:37,566 INFO [decode_test.py:401] batch 0/?, cuts processed until now is 118
2022-05-14 02:24:44,751 INFO [decode_test.py:401] batch 20/?, cuts processed until now is 1859
2022-05-14 02:26:49,527 INFO [decode_test.py:401] batch 40/?, cuts processed until now is 3579
2022-05-14 02:30:33,190 INFO [decode_test.py:401] batch 60/?, cuts processed until now is 5872
2022-05-14 02:34:58,056 INFO [decode_test.py:401] batch 80/?, cuts processed until now is 8436
2022-05-14 02:36:49,084 INFO [decode_test.py:401] batch 100/?, cuts processed until now is 10038
2022-05-14 02:38:54,957 INFO [decode_test.py:401] batch 120/?, cuts processed until now is 11949
2022-05-14 02:41:50,420 INFO [decode_test.py:401] batch 140/?, cuts processed until now is 14046
2022-05-14 02:43:48,539 INFO [decode_test.py:401] batch 160/?, cuts processed until now is 16010
2022-05-14 02:45:45,053 INFO [decode_test.py:401] batch 180/?, cuts processed until now is 17567
2022-05-14 02:47:03,558 INFO [decode_test.py:401] batch 200/?, cuts processed until now is 18926
2022-05-14 02:48:16,578 INFO [decode_test.py:401] batch 220/?, cuts processed until now is 19923
2022-05-14 02:48:17,912 INFO [decode_test.py:418] The transcripts are stored in pruned_transducer_stateless2/exp_500_8/modified_beam_search/recogs-test-beam_size_4-epoch-29-avg-9-beam-4.txt
2022-05-14 02:48:18,602 INFO [utils.py:406] [test-beam_size_4] %WER 10.61% [41453 / 390744, 7550 ins, 9494 del, 24409 sub ]
2022-05-14 02:48:19,594 INFO [decode_test.py:431] Wrote detailed error stats to pruned_transducer_stateless2/exp_500_8/modified_beam_search/errs-test-beam_size_4-epoch-29-avg-9-beam-4.txt
2022-05-14 02:48:19,597 INFO [decode_test.py:452] 
For test, WER of different settings are:
beam_size_4	10.61	best for test

2022-05-14 02:48:19,620 INFO [decode_test.py:577] Done!
```

**Comment by wgb14** [comment]
Update results:
|                                      |  Dev  |  Test   |           |
|--------------------------|-------|--------|------|
|       greedy search         | 10.59 | 10.84 | epoch-29-avg-12 |
|     fast beam search      | 10.55 | 10.79 | epoch-29-avg-15 |
| modified beam search | 10.49 | 10.6 | epoch-29-avg-11 |


Got better results by averaging checkpoints:
|                      |  Dev  | Test  |             |
|----------------------|-------|-------|-----------|
|    greedy search     | 10.51 | 10.73 | iter-3488000-avg-20 |
|   fast beam search   | 10.5 | 10.69 | iter-3488000-avg-20 |
| modified beam search | 10.4 | 10.51 | iter-3488000-avg-15 |

**Comment by wgb14** [comment]
Ready for review now.

The pretrained models in https://huggingface.co/wgb14/icefall-asr-gigaspeech-pruned-transducer-stateless2 are also updated

**Comment by csukuangfj** [comment]
Thanks!

**Comment by csukuangfj** [comment]
@wgb14 
Could you please also upload a torchscript model to
https://huggingface.co/wgb14/icefall-asr-gigaspeech-pruned-transducer-stateless2/tree/main/exp
?

Passing `--jit 1` to the following file should give you an exported torchscript model `cpu_jit.pt`.
https://github.com/k2-fsa/icefall/blob/master/egs/wenetspeech/ASR/pruned_transducer_stateless2/export.py

**Comment by wgb14** [comment]
> 

Sure. will do.

**Comment by csukuangfj** [comment]
> > @wgb14 Could you please also upload a torchscript model to https://huggingface.co/wgb14/icefall-asr-gigaspeech-pruned-transducer-stateless2/tree/main/exp ?
> > Passing `--jit 1` to the following file should give you an exported torchscript model `cpu_jit.pt`. https://github.com/k2-fsa/icefall/blob/master/egs/wenetspeech/ASR/pruned_transducer_stateless2/export.py
> 
> Sure. will do.

Thanks!

**Comment by csukuangfj** [comment]
I have converted it a few days ago and put them in https://huggingface.co/csukuangfj/icefall-asr-gigaspeech-pruned-transducer-stateless2/tree/main/exp

You can copy them to your repo and I will use your repo in some other projects, e.g.,
https://huggingface.co/spaces/k2-fsa/automatic-speech-recognition

**Comment by wgb14** [comment]
> I have converted it a few days ago and put them in https://huggingface.co/csukuangfj/icefall-asr-gigaspeech-pruned-transducer-stateless2/tree/main/exp
> 
> You can copy them to your repo and I will use your repo in some other projects, e.g., https://huggingface.co/spaces/k2-fsa/automatic-speech-recognition

Great, thanks! 

By the way, we ended up using the models averaged from checkpoints, can you also convert to torch scripts and upload them? I actually got some errors when i tried to convert, probably because I messed up my environments after this experiment.

**Comment by csukuangfj** [comment]
> > I have converted it a few days ago and put them in https://huggingface.co/csukuangfj/icefall-asr-gigaspeech-pruned-transducer-stateless2/tree/main/exp
> 
> > 
> 
> > You can copy them to your repo and I will use your repo in some other projects, e.g., https://huggingface.co/spaces/k2-fsa/automatic-speech-recognition
> 
> 
> 
> Great, thanks! 
> 
> 
> 
> By the way, we ended up using the models averaged from checkpoints, can you also convert to torch scripts and upload them? I actually got some errors when i tried to convert, probably because I messed up my environments after this experiment.

Yes, I will do that.

You have to use the latest master for exporting.

**Comment by wgb14** [comment]
> > > I have converted it a few days ago and put them in https://huggingface.co/csukuangfj/icefall-asr-gigaspeech-pruned-transducer-stateless2/tree/main/exp
> > 
> > 
> > > 
> > 
> > 
> > > You can copy them to your repo and I will use your repo in some other projects, e.g., https://huggingface.co/spaces/k2-fsa/automatic-speech-recognition
> > 
> > 
> > Great, thanks!
> > By the way, we ended up using the models averaged from checkpoints, can you also convert to torch scripts and upload them? I actually got some errors when i tried to convert, probably because I messed up my environments after this experiment.
> 
> Yes, I will do that.
> 
> You have to use the latest master for exporting.

Thanks! Uploaded. https://huggingface.co/wgb14/icefall-asr-gigaspeech-pruned-transducer-stateless2/tree/main/exp

**Pull request merged**
