### PR TITLE
Add modified beam search for pruned rnn-t.

### PR DESCRIPTION
**Pull request by csukuangfj**
Training command
```bash
./pruned_transducer_stateless/train.py \
  --world-size 8 \
  --num-epochs 60 \
  --start-epoch 0 \
  --exp-dir pruned_transducer_stateless/exp \
  --full-libri 1 \
  --max-duration 300 \
  --prune-range 5 \
  --lr-factor 5 \
  --lm-scale 0.25
```

Tensorboard log https://tensorboard.dev/experiment/WKRFY5fYSzaVBHahenpNlA/

Decoding command
```bash
for epoch in 42; do
  for avg in 11; do
    ./pruned_transducer_stateless/decode.py \
      --epoch $epoch \
      --avg $avg \
      --exp-dir ./pruned_transducer_stateless/exp \
      --max-duration 100 \
      --decoding-method greedy_search \
      --max-sym-per-frame 1
  done
done

for epoch in 42; do
  for avg in 11; do
    ./pruned_transducer_stateless/decode.py \
      --epoch $epoch \
      --avg $avg \
      --exp-dir ./pruned_transducer_stateless/exp \
      --max-duration 100 \
      --decoding-method modified_beam_search \
      --beam-size 4
  done
done

for epoch in 42; do
  for avg in 11; do
    ./pruned_transducer_stateless/decode.py \
      --epoch $epoch \
      --avg $avg \
      --exp-dir ./pruned_transducer_stateless/exp \
      --max-duration 100 \
      --decoding-method beam_search \
      --beam-size 4
  done
done
```

Decoding results:

|  decoding method                                           | test-clean | test-other | comment                                                     |
|--------------------------------------------|------------|-----------|-----------------------------------------|
| greedy search (--max-sym-per-frame 1)     | 2.62            |  6.37         |--epoch 42 --avg 11 --max-duration 100 |
| greedy search (--max-sym-per-frame 2)      |   2.62         |  6.37        |--epoch 42 --avg 11 --max-duration 100 |
| greedy search (--max-sym-per-frame 3)      |   2.62         |  6.37         |--epoch 42 --avg 11 --max-duration 100 |
| modified beam search (--beam-size 4)      |  2.56            |     6.27     |--epoch 42 --avg 11 --max-duration 100 
| beam search (--beam-size 4)      |    2.57        |  6.27        |--epoch 42 --avg 11 --max-duration 100 |

Note:
1. The model is **not** trained using **modified** transducer.
2. By **modified beam search**, it means it hardcodes `--max-sym-per-frame=1` during beam search.
3. The current implementation of beam search is super slow and we recommend using only modified beam search.
4. For the decoding time of `test-clean` and `test-other`:

| decoding method | test-clean (seconds) | test-other (seconds)|
|---|---:|---:|
| greedy search (--max-sym-per-frame=1) | 160 | 159 |
| greedy search (--max-sym-per-frame=2) | 184 | 177 |
| greedy search (--max-sym-per-frame=3) | 210 | 213 |
| modified beam search (--beam-size 4)| 273 | 269 |
|beam search (--beam-size 4) | 2741 | 2221 |

Will update RESULTS.md and upload the pre-trained model to hugging face later today.

### CODE REVIEW

**Comment by pkufool** [comment]
Does this model contain extra nn.Linear()?

**Comment by csukuangfj** [comment]
> Does this model contain extra nn.Linear()?

Yes. It uses the code from the master.

**Comment by csukuangfj** [comment]
A pre-trained model, the decoding logs, and the decoding results are uploaded to
https://huggingface.co/csukuangfj/icefall-asr-librispeech-pruned-transducer-stateless-2022-03-12

**Comment by danpovey** [comment]
A great feature!

**Pull request merged**
