### PR TITLE
WIP: Begin to add RNNLM.

### PR DESCRIPTION
**Pull request by csukuangfj**
- [x] Finish the dataset part.
- [x] Training
- [x] Calculate perplexity of the validation set
- [ ]  Add LM for the LibriSpeech recipe

### CODE REVIEW

**Comment by ezerhouni** [comment]
@csukuangfj Would it be possible for me to (try) help you on this PR ?

**Comment by csukuangfj** [comment]
> @csukuangfj Would it be possible for me to (try) help you on this PR ?

Sure, you are very welcome. 

Are you going to use it for conformer CTC or for our pruned RNN-T setup?

**Comment by ezerhouni** [comment]
I was thinking for conformer CTC at first, then see if I can help on the n-gram rescoring in beam search (https://github.com/k2-fsa/icefall/pull/365)

**Comment by csukuangfj** [comment]
> I was thinking for conformer CTC at first, then see if I can help on the n-gram rescoring in beam search (#365)

Thanks!

**Comment by ezerhouni** [comment]
@csukuangfj I am refactoring the code a bit to have similar pattern for training the RNN as for the other model (RNN-T, Conformer CTC, etc). Is it the correct approach or there is a reason for keep it the original way ?

**Comment by csukuangfj** [comment]
> @csukuangfj I am refactoring the code a bit to have similar pattern for training the RNN as for the other model (RNN-T, Conformer CTC, etc). Is it the correct approach or there is a reason for keep it the original way ?

You can refactor it to whatever you think is appropriate.

**Comment by ezerhouni** [comment]
Btw, I think this one can be closed @csukuangfj

**Pull request closed without merging**
