### PR TITLE
Replace deprecated pytorch methods

### PR DESCRIPTION
**Pull request by lipeng31**
- torch.cuda.amp.GradScaler(...) => torch.amp.GradScaler("cuda", ...)
- torch.cuda.amp.autocast(...) => torch.amp.autocast("cuda", ...)

### CODE REVIEW

**Comment by csukuangfj** [comment]
could you make it backward compatible?

**Comment by lipeng31** [comment]
I read the PyTorch docs and found the first version that provides both `torch.cuda.amp.autocast` and `torch.cuda.amp.GradScaler` is 1.6.0, and the first version that provides `torch.amp.autocast("cuda", ...)` and `torch.amp.GradSclaer("cuda", ...)` is 1.10.0 which was released 3 years ago, so the compatibility problem happens only for the versions of [1.6.0,1.10.0). I'm not sure if this icefall is supposed to support those versions of PyTorch. Additionally, maintaining compatibility with those versions of PyTorch would require numerous changes throughout the codebase, potentially making the code less clean. Could you reconsider the necessity of this compatibility? Thanks.

**Comment by lipeng31** [comment]
Last commit fails some checks. I'll fix it soon.

**Comment by lipeng31** [comment]
Hi @csukuangfj , I have completed the code revision. There are some checks that still haven't passed, which I believe are unrelated to the changes I've made. Could you please review the pull request? Thank you.

**Review by csukuangfj — APPROVED** [review]
Thank you for your contribution!

**Comment by csukuangfj** [comment]
@lipeng31 Could you resolve the conflicts?

**Comment by lipeng31** [comment]
> @lipeng31 Could you resolve the conflicts?

Conflicts resolved, please review it, thanks.

**Review by csukuangfj — APPROVED** [review]
Thank you!

**Comment by csukuangfj** [comment]
> the first version that provides torch.amp.autocast("cuda", ...) and torch.amp.GradSclaer("cuda", ...) is 1.10.0 which was released 3 years ago

@lipeng31 

I just found the first version was torch 2.3.0, not 1.10.0.

Could you check it again?

**Comment by csukuangfj** [comment]
@lipeng31 sorry, we are going to revert this PR so that users using torch < 2.3.0 can still use icefall without any errors.

The CI tests are using torch>2.3.0 so this PR passes the CI tests.

**Comment by csukuangfj** [comment]
@lipeng31 
Please use
```python3
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)
```
to suppress the warnings.

**Pull request merged**
