### PR TITLE
Modified prepare_transcripts.py and preprare_lexicon.py of tedlium3 recipe

### PR DESCRIPTION
**Pull request by shcxlee**
This PR fixes FileNotFoundError in tedlium3 recipe.

### CODE REVIEW

**Comment by csukuangfj** [comment]
Could you please fix the style issues reported by GitHub actions?

**Comment by shcxlee** [comment]
Sure. I will fix those.

**Review by shcxlee — COMMENTED** [review]
I deleted
````
import json
````
in both files as the style checker said it is imported but not used in both of them.

**Comment by csukuangfj** [comment]
Thanks!

**Pull request merged**
