### PR TITLE
Add Blankskip to Zipformer+CTC

### PR DESCRIPTION
**Pull request by yfyeung**
Accelerating RNN-T Training and Inference Using CTC guidance
https://arxiv.org/abs/2210.16481

### CODE REVIEW

**Comment by kobenaxie** [comment]
Hi, yifan, why not reduce frames at middle layers ?

**Review by csukuangfj — CHANGES_REQUESTED** [review]
Please add `.DS_Store` to `.gitignore`.

**Comment by kobenaxie** [comment]
> Hi, yifan, why not reduce frames at middle layers ?

And  another question, is it possible the reduced encoder frames shorter than label sequence(For the case deletion error in CTC) ?

**Comment by yfyeung** [comment]
> Please add `.DS_Store` to `.gitignore`.

OK

**Pull request closed without merging**
