### PR TITLE
[Ready to merge] Do some coding style checks for the latest files

### PR DESCRIPTION
**Pull request by luomingshuang**
I take some time to do some coding style checks for the latest files.

### CODE REVIEW

**Comment by csukuangfj** [comment]
Thanks! Could you do more fixes, i.e., the one reported by GitHub actions?

**Comment by luomingshuang** [comment]
> Thanks! Could you do more fixes, i.e., the one reported by GitHub actions?

OK. I am doing it.

**Comment by luomingshuang** [comment]
Some changes are done by me, and some changes are done by pre-commit.

**Comment by csukuangfj** [comment]
Thanks

**Comment by luomingshuang** [comment]
It seems that there are some issues in yesno recipe.
```
File "/home/runner/work/icefall/icefall/egs/yesno/ASR/tdnn/asr_datamodule.py", line 243, in train_cuts
    cuts_train = load_manifest(self.args.feature_dir / "cuts_train.json.gz")
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/lhotse/serialization.py", line 3[79](https://github.com/k2-fsa/icefall/runs/6523097508?check_suite_focus=true#step:7:80), in load_manifest
    raw_data = load_json(path)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/lhotse/serialization.py", line 69, in load_json
    with open_best(path) as f:
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/lhotse/serialization.py", line 30, in open_best
    return open_fn(path, mode)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/lhotse/workarounds.py", line 108, in gzip_open_robust
    binary_file = AltGzipFile(filename, gz_mode, compresslevel)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/gzip.py", line 173, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'data/fbank/cuts_train.json.gz'
```

**Comment by csukuangfj** [comment]
> It seems that there are some issues in yesno recipe.

Could you change

https://github.com/k2-fsa/icefall/blob/2900ed8f8f2426040a60e882317b7fc4d4b2f1c9/egs/yesno/ASR/local/compute_fbank_yesno.py#L40-L42

to

```python3
    manifests = read_manifests_if_cached(
        dataset_parts=dataset_parts,
        output_dir=src_dir,
        prefix="yesno",
    )
```

**Comment by luomingshuang** [comment]
Oh, nice. The issue is solved.

**Pull request merged**
