### PR TITLE
[WIP]Vq on reworked model

### PR DESCRIPTION
**Pull request by glynpu**
Current code is modified from a draft what I was using, and will be tested if GPU is available. 

Following experiments are performed with the draft code and clean-100h subset. 

Results with command`grep -A1 %WER modified_beam_search/errs-test-*-beam_size_4-epoch-19-avg-10-beam-4.txt 
`:

```
baseline no vq:

modified_beam_search/errs-test-clean-beam_size_4-epoch-19-avg-10-beam-4.txt:%WER = 7.08
modified_beam_search/errs-test-clean-beam_size_4-epoch-19-avg-10-beam-4.txt-Errors: 410 insertions, 347 deletions, 2963 substitutions, over 52576 reference words (49266 correct)
--
modified_beam_search/errs-test-other-beam_size_4-epoch-19-avg-10-beam-4.txt:%WER = 18.66
modified_beam_search/errs-test-other-beam_size_4-epoch-19-avg-10-beam-4.txt-Errors: 956 insertions, 1097 deletions, 7713 substitutions, over 52343 reference words (43533 correct)


With vq from HuBERT extra large fine-tuned model:


modified_beam_search/errs-test-clean-beam_size_4-epoch-19-avg-10-beam-4.txt:%WER = 5.68
modified_beam_search/errs-test-clean-beam_size_4-epoch-19-avg-10-beam-4.txt-Errors: 286 insertions, 258 deletions, 2444 substitutions, over 52576 reference words (49874 correct)
--
modified_beam_search/errs-test-other-beam_size_4-epoch-19-avg-10-beam-4.txt:%WER = 15.80
modified_beam_search/errs-test-other-beam_size_4-epoch-19-avg-10-beam-4.txt-Errors: 797 insertions, 875 deletions, 6597 substitutions, over 52343 reference words (44871 correct)

```

### CODE REVIEW

**Comment by danpovey** [comment]
@pzelasko Here is that recipe.

**Comment by pzelasko** [comment]
Thanks!

**Comment by glynpu** [comment]
Now results are quite reproducible after fixing some bugs:
Result of first run:
```
errs-test-clean-beam_size_4-epoch-19-avg-10-beam-4.txt:%WER = 5.61
errs-test-other-beam_size_4-epoch-19-avg-10-beam-4.txt:%WER = 15.95
```
second run:
```
errs-test-clean-beam_size_4-epoch-19-avg-10-beam-4.txt:%WER = 5.67
errs-test-other-beam_size_4-epoch-19-avg-10-beam-4.txt:%WER = 15.60
```

**Comment by glynpu** [comment]
Now I am doing some experiment with function "[compute_mask_indices](https://github.com/pytorch/fairseq/blob/c8d6fb198cd58d433cadf178b22afdba40401f13/fairseq/data/data_utils.py#L393)"  to predict masked indices only.

**Comment by danpovey** [comment]
Cool!
I'm hoping we can merge this fairly soon, which will make it easier to keep it up to date when other things change.

**Comment by glynpu** [comment]
Sure. I am implementing your suggestions about predicting indices of masked region only. After that will finalize this pr and make it meargable.

**Pull request closed without merging**
