### PR TITLE
add OTC related scripts using phone as units instead of BPEs

### PR DESCRIPTION
**Pull request by DongjiGao**

### CODE REVIEW

**Comment by JinZr** [comment]
hi, dongji!

is this pr ready to be merged?

**Comment by DongjiGao** [comment]
> hi, dongji!
> 
> is this pr ready to be merged?

Yes. It's ready to be merged. Thanks!

**Comment by JinZr** [comment]
Thanks!

**Review by JinZr — APPROVED** [review]
LGTM

**Pull request merged**
