### PR TITLE
PromptASR for contextualized ASR with controllable style

### PR DESCRIPTION
**Pull request by marcoyang1998**
This is the implementation for PromptASR.

I will add more details in the next few days.

### CODE REVIEW

**Comment by pkufool** [comment]
The paper link: https://arxiv.org/abs/2309.07414

**Comment by marcoyang1998** [comment]
The pre-trained models are uploaded here: 

With context list:
https://huggingface.co/marcoyang/icefall-promptasr-with-context-libriheavy-zipformer-BERT-2023-10-10

Without context list:
https://huggingface.co/marcoyang/icefall-promptasr-libriheavy-zipformer-BERT-2023-10-10

**Comment by marcoyang1998** [comment]
To test the model:

1. **Utterance-level** context biasing:
Download the model from https://huggingface.co/marcoyang/icefall-promptasr-libriheavy-zipformer-BERT-2023-10-10, then execute the command below:

```bash
for use_pre_text in 0,1; do
  python zipformer_prompt_asr/pretrained.py \
    --checkpoint icefall-promptasr-with-context-libriheavy-zipformer-BERT-2023-10-10/pretrained.pt \
    --method modified_beam_search \
    --content-prompt "The topic is about horses." \
    --use-pre-text $use_pre_text \
    --beam-size 4 
    icefall-promptasr-libriheavy-zipformer-BERT-2023-10-10/test_wavs/test.wav
done
```

Decoding result 
| Config | Decoding result  | 
| -------- | ------- |
| use_pre_text=False | One day an old gentleman was writing with him, and a large piece of white paper or rag blew across just on one side of me. |
| use_pre_text=True | One day an old gentleman was **riding** with him, and a large piece of white paper or rag blew across just on one side of me. |

With the prior knowledge about "horse", the model successfully outputted the more logical word _riding_ instead of the word _writing_, despite of their pronunciation similarity.

2. **word-level** context biasing:
Download the model from https://huggingface.co/marcoyang/icefall-promptasr-with-context-libriheavy-zipformer-BERT-2023-10-10, then execute the command below:

```bash
for use_pre_text in 0,1; do
  python zipformer_prompt_asr/pretrained.py \
    --checkpoint icefall-promptasr-with-context-libriheavy-zipformer-BERT-2023-10-10/pretrained.pt \
    --method modified_beam_search \
    --content-prompt "bessy random words hello k2 ASR" \
    --use-pre-text $use_pre_text \
    --style-text-transform mixed-punc \
    --style-prompt "Mixed-case English transcription, with punctuation." \
    --beam-size 4 
    icefall-promptasr-with-context-libriheavy-zipformer-BERT-2023-10-10/test_wavs/librispeech.flac
done
```

| Config | Decoding result  |
| ------- | -------------- | 
| use_pre_text=False | **Bessie** took a long and feverish draught, and then fell back and shut her eyes. |
| use_pre_text=True | **Bessy ** took a long and feverish draught, and then fell back and shut her eyes. |

Given a few context words, the model outputs the correct name _Bessy_.

**Comment by marcoyang1998** [comment]
Merging this now.

**Pull request merged**
