### PR TITLE
Support exporting BS Zipformer models to ONNX, used in Triton Server

### PR DESCRIPTION
**Pull request by wd929**
Hi all,

This PR is to support exporting BS Zipformer models to ONNX, which can be used in Triton Server.
These exported ONNX models can be deployed using Triton in Sherpa. Sherpa link: https://github.com/k2-fsa/sherpa/pull/364

Thanks,
Wen

### CODE REVIEW

**Comment by wd929** [comment]
@csukuangfj @yfyeung hi Fangjun and Yifan, could you please review this PR? Thanks!

**Comment by wd929** [comment]
Differences of previous exporting codes:
1. Not export frame reducer as an individual ONNX model, use a Triton Python backend to implement this module
2. For lconv model, inputs are changed. src_key_padding_mask=> lconv_input_lens since boolean type is not supported in Pytorch to_dlpack
3. Several wrappers added

**Comment by yfyeung** [comment]
> Differences of previous exporting codes:
> 
> 1. Not export frame reducer as an individual ONNX model, use a Triton Python backend to implement this module
> 2. For lconv model, inputs are changed. src_key_padding_mask=> lconv_input_lens since boolean type is not supported in Pytorch to_dlpack
> 3. Several wrappers added

OK, I have added an if branch to bypass the export_frame_reducer when using Triton and changed several comments.

**Review by yfyeung — APPROVED** [review]
Thanks!

**Comment by wd929** [comment]
Thanks Yifan!

**Pull request merged**
