### PR TITLE
Add pruned RNN-T for aishell.

### PR DESCRIPTION
**Pull request by csukuangfj**
Using [aidatatang_200zh](https://openslr.org/62/) as extra training data.

### CODE REVIEW

**Comment by danpovey** [comment]
Cool.  So --avg 5 was the optimum?  Seems lower than normal.  It's OK that the WER is a tiny fraction worse, we could do better by having more epochs, probably, but let's get in the habit of not doing that, to save time.  What is context-length?

**Comment by csukuangfj** [comment]
> Cool. So --avg 5 was the optimum? 

Yes.

The model was first trained for 30 epochs and then it was resumed and was trained for another 10 epochs.

You see that it improves only a bit, so I choose `epoch 29 avg 5`
```
(py38) kuangfangjun:modified_beam_search$ grep -r -n --color "best for test" log-* | sort -n -k2 | head -n10
log-decode-epoch-35-avg-5-modified_beam_search-beam-size-4-use-averaged-model-2022-06-20-16-31-42:19:beam_size_4        5.03    best for test
log-decode-epoch-29-avg-5-modified_beam_search-beam-size-4-use-averaged-model-2022-06-19-12-31-39:19:beam_size_4        5.05    best for test
log-decode-epoch-35-avg-6-modified_beam_search-beam-size-4-use-averaged-model-2022-06-20-16-49-49:19:beam_size_4        5.05    best for test
log-decode-epoch-38-avg-3-modified_beam_search-beam-size-4-use-averaged-model-2022-06-20-11-06-48:19:beam_size_4        5.05    best for test
log-decode-epoch-35-avg-4-modified_beam_search-beam-size-4-use-averaged-model-2022-06-20-16-15-29:19:beam_size_4        5.06    best for test
log-decode-epoch-35-avg-7-modified_beam_search-beam-size-4-use-averaged-model-2022-06-20-17-08-39:19:beam_size_4        5.06    best for test
log-decode-epoch-38-avg-4-modified_beam_search-beam-size-4-use-averaged-model-2022-06-20-11-21-57:19:beam_size_4        5.06    best for test
log-decode-epoch-39-avg-4-modified_beam_search-beam-size-4-use-averaged-model-2022-06-20-07-57-35:19:beam_size_4        5.06    best for test
log-decode-epoch-29-avg-4-modified_beam_search-beam-size-4-use-averaged-model-2022-06-19-12-13-36:19:beam_size_4        5.07    best for test
log-decode-epoch-29-avg-6-modified_beam_search-beam-size-4-use-averaged-model-2022-06-19-12-49-41:19:beam_size_4        5.1     best for test
```

**Comment by danpovey** [comment]
Cool.
For new experiment directories, can we use that change that Zengwei tested, where the linear layers in the RandomCombine module are removed?

**Comment by csukuangfj** [comment]
> I anticipate the difference will be smaller for larger-data setups.

Yes, I believe so. The wenetspeech recipe is using context size 2, I think.

---

> I anticipate the difference will be smaller for larger-data setups.

Sure.

**Pull request merged**
