### PR TITLE
Support exporting RNNLM to ONNX.

### PR DESCRIPTION
**Pull request by csukuangfj**
# Usage of this PR

## Export the model to ONNX

```bash
if [ ! -f ./icefall-librispeech-rnn-lm/exp/pretrained.pt ]; then
  GIT_LFS_SKIP_SMUDGE=1 git clone https://huggingface.co/ezerhouni/icefall-librispeech-rnn-lm
  pushd icefall-librispeech-rnn-lm/exp
  git lfs pull --include "pretrained.pt"
  ln -s pretrained.pt epoch-99.pt
  popd
fi

python3 ./export-onnx.py \
  --exp-dir ./icefall-librispeech-rnn-lm/exp \
  --epoch 99 \
  --avg 1 \
  --vocab-size 500 \
  --embedding-dim 2048 \
  --hidden-dim 2048 \
  --num-layers 3 \
  --tie-weights 1
```

## Check the exported ONNX model
```bash
./check-onnx.py \
  --jit ./icefall-librispeech-rnn-lm/exp/cpu_jit.pt \
  --onnx ./icefall-librispeech-rnn-lm/exp/no-state-epoch-99-avg-1.onnx
```

Will test it in [sherpa-onnx](https://github.com/k2-fsa/sherpa-onnx)

---

Note: The first step is to use it to rescore a complete sentence.

---

# model file sizes

```bash
-rw-r--r-- 1 kuangfangjun root 389M Apr 19 21:28 cpu_jit.pt
-rw-r--r-- 1 kuangfangjun root  99M Apr 20 13:53 no-state-epoch-99-avg-1.int8.onnx
-rw-r--r-- 1 kuangfangjun root 393M Apr 20 13:52 no-state-epoch-99-avg-1.onnx
-rw-r--r-- 1 kuangfangjun root 389M Apr 19 21:23 pretrained.pt
```

### CODE REVIEW

**Comment by csukuangfj** [comment]
@ezerhouni 

Could you please merge the pull-request at https://huggingface.co/ezerhouni/icefall-librispeech-rnn-lm/discussions/1
which uploads ONNX models exported by this PR.

**Comment by csukuangfj** [comment]
Please see
https://github.com/k2-fsa/sherpa-onnx/pull/125
for how to use models exported by this PR.

**Comment by ezerhouni** [comment]
@csukuangfj I merged your PR. Thank you for taking care of it.

**Comment by csukuangfj** [comment]
> https://huggingface.co/ezerhouni/icefall-librispeech-rnn-lm/discussions/2

@ezerhouni 
There are two more PRs in https://huggingface.co/ezerhouni/icefall-librispeech-rnn-lm/discussions

Could you please merge them? Thanks!

**Comment by ezerhouni** [comment]
@csukuangfj Done !

**Pull request merged**
